# -*- coding: utf-8 -*-
r"""
Генератор исходника Windows-прототипа «ЯВЬ: Забытые Былины».
Все русские строки переводятся в pure-ASCII escape-последовательности
(UTF-16 code units), поэтому mingw-gcc компилирует файл без проблем
с локалью/кодировкой.
Запуск:  python3 Prototype/gen.py && bash Prototype/build.sh
"""
import re

def w(s: str) -> str:
    """C-широкая строка из unicode, полностью ASCII-safe."""
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif ch == '\n':
            out.append('\\n')
        elif o < 128:
            out.append(ch)
        else:
            out.append('\\x%04x' % o)
    return 'L"' + ''.join(out) + '"'

TITLE      = "ЯВЬ: Забытые Былины"
SUBTITLE   = "Прототип v0.1 — окно запуска и выбор героя"
S_LOGO     = "Я В Ь"
S_SLOGAN   = "Забытые Былины зовут"
B_START    = "НАЧАТЬ ИГРУ"
B_LORE     = "ПРЕДАНИЕ"
B_EXIT     = "ВЫХОД"
H_SELECT   = "Выбери былину — героя по сердцу"
H_NAME     = "Имя героя:"
B_BACK     = "Назад"
B_CHOOSE   = "ВЫБРАТЬ ГЕРОЯ"
B_NEED     = "Сначала выбери героя"
H_READY1   = "Земля Навь ждёт былину!"
H_READY2   = "Герой выбран"
H_READY3   = "Профиль сохранён в файловую БД (yav_profile.json)"
H_NICKWARN = "Введите имя героя!"
B_OK       = "ПОНЯТНО"

LORE = ("Давно это было, иль только снится?\n"
        "Колодезь времён мутил воду, и стёрлась\n"
        "между Явью и Навью тонкая грань.\n"
        "\n"
        "Забыты имена богатырей, потухли\n"
        "костры в пустых деревнях, а былины\n"
        "спят на дне чёрных озёр.\n"
        "\n"
        "Но Навь не спит. Она подсылает нежить,\n"
        "морочит лес, манит к себе.\n"
        "\n"
        "Вставай, былинушка. Пока помнят — живы.")

CLASSES = [
    dict(name="Богатырь", tag="Танк / ближний бой", color=(0x2F, 0x3A, 0x8B),
         hp=150, dmg=18, energy=60, carry=50,
         desc=("Крестьянский сын, поднявший дубовую палицу. Крепкий телом, "
               "идёт вперёд — рубит нежить в ближнем бою и носит больше всех лута.")),
    dict(name="Стрелок", tag="Дальний физический урон", color=(0x3A, 0x6B, 0x3F),
         hp=100, dmg=24, energy=80, carry=20,
         desc=("Охотник-следопыт из глухих лесов. Бьёт издалека точной стрелой, "
               "быстро ходит и быстро гибнет вблизи.")),
    dict(name="Волхв", tag="Магия / поддержка", color=(0x7A, 0x4A, 0x4A),
         hp=80, dmg=30, energy=160, carry=0,
         desc=("Носитель древних заговоров. Творит огонь и мороки, но телом немощен. "
               "В группе — поддержка и контроль толпы.")),
]

# ------------------------------------------------------------------ шаблон C
BODY = r"""/* ==========================================================================
 * "YAV: Zabytye Byliny" (ЯВЬ: Забытые Былины) — Windows test build (prototype)
 * --------------------------------------------------------------------------
 * Fixed window 640x480. Launch screen -> Character select (Bogatyr/Strelok/
 * Volkhv) -> ready screen. Class stats mirror Assets/Scripts/Core/CharacterClass.cs
 * (Yav.Core.CharacterClassDef). Progress is dumped to a FILE database
 * (yav_profile.json next to the exe) until a real server DB exists.
 *
 * NOTE: Win32 UI/architecture smoke-test while the Unity project (Assets/)
 * is developed in parallel. Same screens, same data, same flow.
 * Generated by Prototype/gen.py — edit gen.py, not this file.
 * ========================================================================== */
#define WINVER 0x0A00
#define _WIN32_WINNT 0x0A00
#include <windows.h>
#include <stdio.h>
#include <string.h>

#define NCLASS 3
#define WIN_W 640
#define WIN_H 480

#define IDC_BTN_START  101
#define IDC_BTN_LORE   102
#define IDC_BTN_QUIT   103
#define IDC_CARD_0     201
#define IDC_CARD_1     202
#define IDC_CARD_2     203
#define IDC_BTN_BACK   204
#define IDC_BTN_CHOOSE 205
#define IDC_EDT_NICK   206
#define IDC_BTN_OK     207

enum { SCR_LAUNCH, SCR_SELECT, SCR_LORE, SCR_READY };

typedef struct {
    const wchar_t* name;
    const wchar_t* tag;
    const wchar_t* desc;
    COLORREF color;
    int hp, dmg, energy, carry;
} ClassDef;

static ClassDef g_class[NCLASS] = {
CLASS_TABLE
};

static const wchar_t* APP_TITLE = TITLE_STR;
static const wchar_t* S_LOGO    = LOGO_STR;
static const wchar_t* S_SLOGAN  = SLOGAN_STR;
static const wchar_t* S_SUBT    = SUBT_STR;
static const wchar_t* B_START   = BSTRT_STR;
static const wchar_t* B_LORE    = BLEND_STR;
static const wchar_t* B_EXIT    = BEXIT_STR;
static const wchar_t* H_SELECT  = HSEL_STR;
static const wchar_t* H_NAME    = HNAME_STR;
static const wchar_t* B_BACK    = BBACK_STR;
static const wchar_t* B_CHOOSE  = BCHSE_STR;
static const wchar_t* B_NEED    = BNEED_STR;
static const wchar_t* H_READY1  = HRDY1_STR;
static const wchar_t* H_READY2  = HRDY2_STR;
static const wchar_t* H_READY3  = HRDY3_STR;
static const wchar_t* H_WARN    = HWARN_STR;
static const wchar_t* B_OK      = BOK_STR;
static const wchar_t* LORE_TEXT = LORE_STR;

static int  g_screen   = SCR_LAUNCH;
static int  g_selected = -1;
static HWND g_hWnd     = NULL;
static HWND g_editNick = NULL;
static HFONT g_fBig, g_fMed, g_fSmall, g_fTitle;

/* ---------- Файловая БД: дамп выбора в JSON рядом с exe ---------- */
static void SaveProfile(void)
{
    wchar_t wpath[MAX_PATH], nick[64] = L"";
    char apath[MAX_PATH * 3], nutf[256] = "hero";
    FILE* f;
    wchar_t* dot;

    GetModuleFileNameW(NULL, wpath, MAX_PATH);
    dot = wcsrchr(wpath, L'.');
    if (dot) wcscpy(dot, L"_profile.json");
    WideCharToMultiByte(CP_UTF8, 0, wpath, -1, apath, sizeof(apath), NULL, NULL);

    if (g_editNick) GetWindowTextW(g_editNick, nick, 63);
    WideCharToMultiByte(CP_UTF8, 0, nick, -1, nutf, sizeof(nutf), NULL, NULL);

    f = fopen(apath, "w");
    if (!f) return;
    fprintf(f, "{\n  \"nickname\": \"%s\",\n  \"classId\": %d,\n  \"classRu\": \"%ls\"\n}\n",
            nutf, g_selected, g_selected >= 0 ? g_class[g_selected].name : L"?");
    fclose(f);
}

/* ------------------------------ Rendering -------------------------------- */
/* Простая рамка: 4 линии (не путать с FrameRect, который требует кисть!) */
static void DrawFrame(HDC hdc, RECT rc, COLORREF col, int thick)
{
    HPEN p = CreatePen(PS_SOLID, thick, col);
    HPEN old = SelectObject(hdc, p);
    SetBkMode(hdc, TRANSPARENT);
    MoveToEx(hdc, rc.left,  rc.top,    NULL);
    LineTo(hdc,  rc.right,  rc.top);
    LineTo(hdc,  rc.right,  rc.bottom);
    LineTo(hdc,  rc.left,   rc.bottom);
    LineTo(hdc,  rc.left,   rc.top);
    SelectObject(hdc, old);
    DeleteObject(p);
}

static void DrawGradient(HDC hdc, RECT r, COLORREF c1, COLORREF c2)
{
    TRIVERTEX v[2]; GRADIENT_RECT gr;
    v[0].x = r.left;  v[0].y = r.top;
    v[0].Red = GetRValue(c1)*256; v[0].Green = GetGValue(c1)*256; v[0].Blue = GetBValue(c1)*256; v[0].Alpha = 0;
    v[1].x = r.right; v[1].y = r.bottom;
    v[1].Red = GetRValue(c2)*256; v[1].Green = GetGValue(c2)*256; v[1].Blue = GetBValue(c2)*256; v[1].Alpha = 0;
    gr.UpperLeft = 0; gr.LowerRight = 1;
    GradientFill(hdc, v, 2, &gr, 1, GRADIENT_FILL_RECT_V);
}

static void CenterText(HDC hdc, const wchar_t* s, int cx, int cy, COLORREF col, HFONT f)
{
    SIZE sz; SetTextColor(hdc, col); SelectObject(hdc, f);
    GetTextExtentPoint32W(hdc, s, (int)wcslen(s), &sz);
    TextOutW(hdc, cx - sz.cx/2, cy, s, (int)wcslen(s));
}

static void PaintScreen(HDC hdc)
{
    RECT rc = {0,0,WIN_W,WIN_H};
    int i, x, y;
    DrawGradient(hdc, rc, RGB(9,12,24), RGB(30,22,44));
    /* звёзды (детерминированные) */
    for (i = 0; i < 60; i++) {
        x = (i*137 + 29) % WIN_W;
        y = (i*89  + 13) % (WIN_H/2);
        SetPixel(hdc, x, y, RGB(110,112,150));
    }

    switch (g_screen) {
    case SCR_LAUNCH:
        CenterText(hdc, S_LOGO,   WIN_W/2, 84,  RGB(235,225,190), g_fTitle);
        CenterText(hdc, S_SLOGAN, WIN_W/2, 156, RGB(170,160,190), g_fMed);
        CenterText(hdc, S_SUBT,   WIN_W/2, 434, RGB(110,110,130), g_fSmall);
        break;
    case SCR_SELECT:
        CenterText(hdc, H_SELECT, WIN_W/2, 14, RGB(235,225,190), g_fMed);
        break;
    case SCR_LORE:
        break;
    case SCR_READY: {
        wchar_t line[160];
        CenterText(hdc, H_READY1, WIN_W/2, 120, RGB(240,220,160), g_fBig);
        if (g_selected >= 0) {
            wsprintfW(line, L"%ls: %ls", H_READY2, g_class[g_selected].name);
            CenterText(hdc, line, WIN_W/2, 190, RGB(220,220,235), g_fMed);
            CenterText(hdc, H_READY3, WIN_W/2, 230, RGB(140,170,140), g_fSmall);
        }
        break; }
    }
}

/* --------------------------- Контролы экранов ---------------------------- */
static BOOL CALLBACK DestroyChild(HWND h, LPARAM p)
{
    (void)h; (void)p;
    DestroyWindow(h);
    return TRUE;
}

static void ClearControls(void)
{
    EnumChildWindows(g_hWnd, DestroyChild, 0);
    g_editNick = NULL;
}

static HWND MkBtn(int id, int x, int y, int wdt, int hgt)
{
    return CreateWindowExW(0, L"BUTTON", L"",
        WS_CHILD|WS_VISIBLE|BS_OWNERDRAW, x, y, wdt, hgt,
        g_hWnd, (HMENU)(INT_PTR)id, NULL, NULL);
}

static void BuildScreen(void)
{
    switch (g_screen) {
    case SCR_LAUNCH:
        MkBtn(IDC_BTN_START, 220, 220, 200, 46);
        MkBtn(IDC_BTN_LORE,  220, 278, 200, 46);
        MkBtn(IDC_BTN_QUIT,  220, 336, 200, 46);
        break;
    case SCR_SELECT:
        MkBtn(IDC_CARD_0,  14, 78, 196, 250);
        MkBtn(IDC_CARD_1, 222, 78, 196, 250);
        MkBtn(IDC_CARD_2, 430, 78, 196, 250);
        MkBtn(IDC_BTN_BACK,   14, 424, 110, 40);
        MkBtn(IDC_BTN_CHOOSE, 430, 424, 196, 40);
        CreateWindowExW(0, L"STATIC", H_NAME, WS_CHILD|WS_VISIBLE|SS_RIGHT,
            20, 388, 120, 22, g_hWnd, NULL, NULL, NULL);
        g_editNick = CreateWindowExW(WS_EX_CLIENTEDGE, L"EDIT", L"",
            WS_CHILD|WS_VISIBLE|ES_AUTOHSCROLL, 150, 384, 480, 28,
            g_hWnd, (HMENU)IDC_EDT_NICK, NULL, NULL);
        SendMessageW(g_editNick, WM_SETFONT, (WPARAM)g_fMed, TRUE);
        break;
    case SCR_LORE:
        MkBtn(IDC_BTN_OK, 240, 428, 160, 38);
        break;
    case SCR_READY:
        MkBtn(IDC_BTN_BACK, 240, 320, 160, 40);
        break;
    }
    InvalidateRect(g_hWnd, NULL, TRUE);
}

static void GoScreen(int s)
{
    g_screen = s;
    ClearControls();
    BuildScreen();
}

/* ------------------------------ Кнопки ----------------------------------- */
static void DrawCard(LPDRAWITEMSTRUCT dis, int idx)
{
    HDC hdc = dis->hDC; RECT rc = dis->rcItem;
    BOOL sel = (g_selected == idx);
    BOOL hot = (dis->itemState & (ODS_HOTLIGHT|ODS_SELECTED)) != 0;
    HBRUSH b = CreateSolidBrush(sel ? g_class[idx].color : (hot ? RGB(58,66,96) : RGB(24,28,46)));
    FillRect(hdc, &rc, b); DeleteObject(b);
    DrawFrame(hdc, rc, sel ? RGB(240,220,160) : RGB(72,76,100), sel ? 3 : 1);
    SetBkMode(hdc, TRANSPARENT);
    CenterText(hdc, g_class[idx].name, (rc.left+rc.right)/2, rc.top+12, RGB(240,238,245), g_fBig);
    CenterText(hdc, g_class[idx].tag,   (rc.left+rc.right)/2, rc.top+46, RGB(180,180,195), g_fSmall);
    {
        RECT dr = { rc.left+12, rc.top+74, rc.right-12, rc.bottom-34 };
        SetTextColor(hdc, RGB(208,208,220)); SelectObject(hdc, g_fSmall);
        DrawTextW(hdc, g_class[idx].desc, -1, &dr, DT_WORDBREAK|DT_LEFT);
    }
    {
        wchar_t st[96];
        wsprintfW(st, L"HP %d  \x2022  DMG %d  \x2022  MANA %d  \x2022  LOOT +%d",
                  g_class[idx].hp, g_class[idx].dmg, g_class[idx].energy, g_class[idx].carry);
        CenterText(hdc, st, (rc.left+rc.right)/2, rc.bottom-28, RGB(160,205,160), g_fSmall);
    }
}

static void DrawLabelButton(LPDRAWITEMSTRUCT dis, const wchar_t* label, COLORREF base)
{
    HDC hdc = dis->hDC; RECT rc = dis->rcItem;
    BOOL hot = (dis->itemState & (ODS_HOTLIGHT|ODS_SELECTED)) != 0;
    HBRUSH b = CreateSolidBrush(hot ? RGB(96,74,42) : base);
    FillRect(hdc, &rc, b); DeleteObject(b);
    DrawFrame(hdc, rc, RGB(130,130,160), 1);
    SetBkMode(hdc, TRANSPARENT);
    {
        SIZE sz; SetTextColor(hdc, RGB(238,238,242)); SelectObject(hdc, g_fMed);
        GetTextExtentPoint32W(hdc, label, (int)wcslen(label), &sz);
        TextOutW(hdc, rc.left+(rc.right-rc.left)/2 - sz.cx/2,
                     rc.top +(rc.bottom-rc.top )/2 - sz.cy/2, label, (int)wcslen(label));
    }
}

static void HandleDrawItem(LPDRAWITEMSTRUCT dis)
{
    switch (dis->CtlID) {
    case IDC_BTN_START:  DrawLabelButton(dis, B_START, RGB(44,52,78));  break;
    case IDC_BTN_LORE:   DrawLabelButton(dis, B_LORE,  RGB(44,52,78));  break;
    case IDC_BTN_QUIT:   DrawLabelButton(dis, B_EXIT,  RGB(64,36,40));  break;
    case IDC_BTN_BACK:   DrawLabelButton(dis, B_BACK,  RGB(44,52,78));  break;
    case IDC_BTN_OK:     DrawLabelButton(dis, B_OK,    RGB(44,52,78));  break;
    case IDC_BTN_CHOOSE: DrawLabelButton(dis, g_selected>=0 ? B_CHOOSE : B_NEED, RGB(52,60,44)); break;
    case IDC_CARD_0: case IDC_CARD_1: case IDC_CARD_2:
        DrawCard(dis, dis->CtlID - IDC_CARD_0); break;
    }
}

/* ------------------------------- Lore-экран ------------------------------ */
static void PaintLore(HDC hdc)
{
    RECT rc = {0,0,WIN_W,WIN_H}, tr = {40, 24, 600, 410};
    DrawGradient(hdc, rc, RGB(14,12,26), RGB(26,20,38));
    SetBkMode(hdc, TRANSPARENT);
    SetTextColor(hdc, RGB(214,206,186));
    SelectObject(hdc, g_fSmall);
    DrawTextW(hdc, LORE_TEXT, -1, &tr, DT_LEFT|DT_WORDBREAK);
}

/* -------------------------------- WndProc -------------------------------- */
static LRESULT CALLBACK WndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    switch (msg) {
    case WM_CREATE: {
        NONCLIENTMETRICSW ncm; ZeroMemory(&ncm, sizeof(ncm)); ncm.cbSize = sizeof(ncm);
        SystemParametersInfoW(SPI_GETNONCLIENTMETRICS, sizeof(ncm), &ncm, 0);
        g_fBig   = CreateFontW(-24,0,0,0,FW_SEMIBOLD,0,0,0,DEFAULT_CHARSET,0,0,ANTIALIASED_QUALITY,0,ncm.lfMessageFont.lfFaceName);
        g_fMed   = CreateFontW(-17,0,0,0,FW_NORMAL,  0,0,0,DEFAULT_CHARSET,0,0,ANTIALIASED_QUALITY,0,ncm.lfMessageFont.lfFaceName);
        g_fSmall = CreateFontW(-14,0,0,0,FW_NORMAL,  0,0,0,DEFAULT_CHARSET,0,0,ANTIALIASED_QUALITY,0,ncm.lfMessageFont.lfFaceName);
        g_fTitle = CreateFontW(-54,0,0,0,FW_BOLD,    0,0,0,DEFAULT_CHARSET,0,0,ANTIALIASED_QUALITY,0,L"Georgia");
        g_hWnd = hWnd;
        BuildScreen();
        return 0;
    }
    case WM_PAINT: {
        PAINTSTRUCT ps; HDC hdc = BeginPaint(hWnd, &ps);
        HDC mem = CreateCompatibleDC(hdc);
        HBITMAP bmp = CreateCompatibleBitmap(hdc, WIN_W, WIN_H);
        HBITMAP old = SelectObject(mem, bmp);
        if (g_screen == SCR_LORE) PaintLore(mem); else PaintScreen(mem);
        BitBlt(hdc, 0, 0, WIN_W, WIN_H, mem, 0, 0, SRCCOPY);
        SelectObject(mem, old); DeleteObject(bmp); DeleteDC(mem);
        EndPaint(hWnd, &ps);
        return 0;
    }
    case WM_DRAWITEM:
        if (((LPDRAWITEMSTRUCT)lParam)->CtlType == ODT_BUTTON) {
            HandleDrawItem((LPDRAWITEMSTRUCT)lParam); return TRUE;
        }
        break;
    case WM_CTLCOLORSTATIC: {
        HDC d = (HDC)wParam;
        SetBkMode(d, TRANSPARENT); SetTextColor(d, RGB(210,210,225));
        return (LRESULT)GetStockObject(NULL_BRUSH);
    }
    case WM_COMMAND:
        switch (LOWORD(wParam)) {
        case IDC_BTN_START:  GoScreen(SCR_SELECT); break;
        case IDC_BTN_LORE:   GoScreen(SCR_LORE);   break;
        case IDC_BTN_OK:     GoScreen(SCR_LAUNCH); break;
        case IDC_BTN_QUIT:   DestroyWindow(hWnd);  break;
        case IDC_CARD_0: case IDC_CARD_1: case IDC_CARD_2:
            g_selected = LOWORD(wParam) - IDC_CARD_0;
            InvalidateRect(hWnd, NULL, FALSE);
            {
                HWND hc = GetDlgItem(hWnd, IDC_BTN_CHOOSE);
                if (hc) InvalidateRect(hc, NULL, TRUE);
            }
            break;
        case IDC_BTN_CHOOSE:
            if (g_selected < 0) { MessageBoxW(hWnd, H_WARN, APP_TITLE, MB_OK|MB_ICONWARNING); break; }
            SaveProfile();
            GoScreen(SCR_READY);
            break;
        case IDC_BTN_BACK:
            GoScreen(SCR_LAUNCH);
            break;
        }
        return 0;
    case WM_DESTROY:
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcW(hWnd, msg, wParam, lParam);
}

int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrev, LPSTR lpCmd, int nShow)
{
    WNDCLASSW wc; MSG m; RECT rw; DWORD style; HWND hWnd;
    ZeroMemory(&wc, sizeof(wc));
    (void)hPrev; (void)lpCmd;
    wc.lpfnWndProc   = WndProc;
    wc.hInstance     = hInst;
    wc.hCursor       = LoadCursor(NULL, IDC_ARROW);
    wc.hbrBackground = NULL;
    wc.lpszClassName = L"YavProtoWnd";
    RegisterClassW(&wc);

    style = WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX;
    rw.left = 0; rw.top = 0; rw.right = WIN_W; rw.bottom = WIN_H;
    AdjustWindowRect(&rw, style, FALSE);
    hWnd = CreateWindowExW(0, wc.lpszClassName, APP_TITLE, style,
        CW_USEDEFAULT, CW_USEDEFAULT, rw.right-rw.left, rw.bottom-rw.top,
        NULL, NULL, hInst, NULL);
    ShowWindow(hWnd, nShow);
    UpdateWindow(hWnd);

    while (GetMessageW(&m, NULL, 0, 0)) {
        TranslateMessage(&m);
        DispatchMessageW(&m);
    }
    return (int)m.wParam;
}
"""

table = ""
for c in CLASSES:
    table += "    { %s, %s, %s, RGB(0x%02X,0x%02X,0x%02X), %d, %d, %d, %d },\n" % (
        w(c["name"]), w(c["tag"]), w(c["desc"]),
        c["color"][0], c["color"][1], c["color"][2],
        c["hp"], c["dmg"], c["energy"], c["carry"])

src = BODY.replace("CLASS_TABLE", table)
repl = {
    "TITLE_STR": w(TITLE), "LOGO_STR": w(S_LOGO), "SLOGAN_STR": w(S_SLOGAN),
    "SUBT_STR": w(SUBTITLE), "BSTRT_STR": w(B_START), "BLEND_STR": w(B_LORE),
    "BEXIT_STR": w(B_EXIT), "HSEL_STR": w(H_SELECT), "HNAME_STR": w(H_NAME),
    "BBACK_STR": w(B_BACK), "BCHSE_STR": w(B_CHOOSE), "BNEED_STR": w(B_NEED),
    "HRDY1_STR": w(H_READY1), "HRDY2_STR": w(H_READY2), "HRDY3_STR": w(H_READY3),
    "HWARN_STR": w(H_NICKWARN), "BOK_STR": w(B_OK), "LORE_STR": w(LORE),
}
for k, v in repl.items():
    src = src.replace(k, v)

# проверка: никаких не-ASCII байт быть не должно (комментарии transliterate)
def ascii_comments(text: str) -> str:
    def repl(m):
        s = m.group(0)
        for a, b in (("ЯВЬ", "YAV"), ("Забытые Былины", "Zabytye Byliny"),
                     ("Файловая БД: дамп выбора в JSON рядом с exe",
                      "File DB: dump of the choice to JSON next to the exe"),
                     ("Рендер", "Rendering"), ("Контролы экранов", "Screen controls"),
                     ("Кнопки", "Buttons"), ("Lore-экран", "Lore screen"),
                     ("звёзды (детерминированные)", "stars (deterministic)"),
                     ("Простая рамка: 4 линии (не путать с FrameRect, который требует кисть!)",
                      "Simple frame: 4 lines (FrameRect expects a BRUSH, not a pen!)"),
                     ("—", "-")):
            s = s.replace(a, b)
        # если что-то кириллическое осталось — убираем его из комментария
        s = ''.join(ch for ch in s if ord(ch) < 128)
        return s
    return re.sub(r"/\*.*?\*/", repl, text, flags=re.S)

src = ascii_comments(src)
assert all(ord(ch) < 128 for ch in src), "non-ascii leaked into generated C source"

with open('/workspace/Prototype/yav_prototype.c', 'w') as f:
    f.write(src)
print("generated:", len(src), "bytes -> Prototype/yav_prototype.c")
