/* ==========================================================================
 * "YAV: Zabytye Byliny" (YAV: Forgotten Epic Tales) - Windows test build v0.3
 * --------------------------------------------------------------------------
 * Fixed window 640x480. Flow:
 *   Launch screen -> Character select (Bogatyr/Strelek/Volkhv) -> World
 * If a profile file exists next to the exe, player gets "CONTINUE / NEW".
 * Real-time autosave: every action (choice, nickname, movement, quest step)
 * is written to yav_profile.json immediately (atomic write via temp+rename).
 *
 * v0.2: small village scene with an oak tree in the center and the
 * NPC "Cat the Scholar" (Kot Ucheny) who greets the hero and gives the
 * first quest ("Greet the scholar cat" -> "Collect 3 acorns near the oak").
 *
 * v0.3 controls:
 *   - Mouse-to-walk: left-click anywhere on the ground and the hero walks
 *     there automatically (collision-aware: huts, well, oak trunk, bounds).
 *     Arrow keys / WASD still work as manual override.
 *   - Ability hotbar (keys 1..4): class-specific skills with energy cost,
 *     cooldown sweep animation and countdown; passive energy regen (+1/2s);
 *     HP + energy bars in HUD; ESC returns to menu.
 * Architecture note (mirrors Unity project): logic (stats, quest state,
 * persistence) is separated from rendering; later this exact state model
 * moves behind a server-authoritative network layer.
 * Generated by Prototype/gen.py - edit gen.py, not this file.
 * ========================================================================== */
#define WINVER 0x0A00
#define _WIN32_WINNT 0x0A00
#include <windows.h>
#include <windowsx.h>   /* GET_X_LPARAM / GET_Y_LPARAM for mouse-to-walk */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <stdarg.h>
#include <math.h>
#ifndef min
#define min(a,b) ((a)<(b)?(a):(b))
#endif
#ifndef max
#define max(a,b) ((a)>(b)?(a):(b))
#endif

#define NCLASS 3
#define WIN_W 640
#define WIN_H 480

#define IDC_BTN_START  101
#define IDC_BTN_LORE   102
#define IDC_BTN_QUIT   103
#define IDC_CARD_0     201
#define IDC_CARD_1     202
#define IDC_CARD_2     203
#define IDC_BTN_BACK   204
#define IDC_BTN_CHOOSE 205
#define IDC_EDT_NICK   206
#define IDC_BTN_OK     207
#define IDC_BTN_CONT   111
#define IDC_BTN_NEW    112

enum { SCR_LAUNCH, SCR_SELECT, SCR_LORE, SCR_CONTINUE, SCR_WORLD, SCR_PROF };
#define IDC_BTN_P0 301
#define IDC_BTN_P1 302
#define IDC_BTN_P2 303

typedef struct {
    const wchar_t* name;
    const wchar_t* tag;
    const wchar_t* desc;
    COLORREF color;
    int hp, dmg, energy, carry;
} ClassDef;

static ClassDef g_class[NCLASS] = {
    { L"\x0411\x043e\x0433\x0430\x0442\x044b\x0440\x044c", L"\x0422\x0430\x043d\x043a / \x0431\x043b\x0438\x0436\x043d\x0438\x0439 \x0431\x043e\x0439", L"\x041a\x0440\x0435\x0441\x0442\x044c\x044f\x043d\x0441\x043a\x0438\x0439 \x0441\x044b\x043d, \x043f\x043e\x0434\x043d\x044f\x0432\x0448\x0438\x0439 \x0434\x0443\x0431\x043e\x0432\x0443\x044e \x043f\x0430\x043b\x0438\x0446\x0443. \x041a\x0440\x0435\x043f\x043a\x0438\x0439 \x0442\x0435\x043b\x043e\x043c, \x0438\x0434\x0451\x0442 \x0432\x043f\x0435\x0440\x0451\x0434 \x2014 \x0440\x0443\x0431\x0438\x0442 \x043d\x0435\x0436\x0438\x0442\x044c \x0432 \x0431\x043b\x0438\x0436\x043d\x0435\x043c \x0431\x043e\x0435 \x0438 \x043d\x043e\x0441\x0438\x0442 \x0431\x043e\x043b\x044c\x0448\x0435 \x0432\x0441\x0435\x0445 \x043b\x0443\x0442\x0430.", RGB(0x2F,0x3A,0x8B), 150, 18, 60, 50 },
    { L"\x0421\x0442\x0440\x0435\x043b\x043e\x043a", L"\x0414\x0430\x043b\x044c\x043d\x0438\x0439 \x0444\x0438\x0437\x0438\x0447\x0435\x0441\x043a\x0438\x0439 \x0443\x0440\x043e\x043d", L"\x041e\x0445\x043e\x0442\x043d\x0438\x043a-\x0441\x043b\x0435\x0434\x043e\x043f\x044b\x0442 \x0438\x0437 \x0433\x043b\x0443\x0431\x0438\x0445 \x043b\x0435\x0441\x043e\x0432. \x0411\x044c\x0451\x0442 \x0438\x0437\x0434\x0430\x043b\x0435\x043a\x0430 \x0442\x043e\x0447\x043d\x043e\x0439 \x0441\x0442\x0440\x0435\x043b\x043e\x0439, \x0431\x044b\x0441\x0442\x0440\x043e \x0445\x043e\x0434\x0438\x0442 \x0438 \x0431\x044b\x0441\x0442\x0440\x043e \x0433\x0438\x0431\x043d\x0435\x0442 \x0432\x0431\x043b\x0438\x0437\x0438.", RGB(0x3A,0x6B,0x3F), 100, 24, 80, 20 },
    { L"\x0412\x043e\x043b\x0445\x0432", L"\x041c\x0430\x0433\x0438\x044f / \x043f\x043e\x0434\x0434\x0435\x0440\x0436\x043a\x0430", L"\x041d\x043e\x0441\x0438\x0442\x0435\x043b\x044c \x0434\x0440\x0435\x0432\x043d\x0438\x0445 \x0437\x0430\x0433\x043e\x0432\x043e\x0440\x043e\x0432. \x0422\x0432\x043e\x0440\x0438\x0442 \x043e\x0433\x043e\x043d\x044c \x0438 \x043c\x043e\x0440\x043e\x043a\x0438, \x043d\x043e \x0442\x0435\x043b\x043e\x043c \x043d\x0435\x043c\x043e\x0449\x0435\x043d. \x0412 \x0433\x0440\x0443\x043f\x043f\x0435 \x2014 \x043f\x043e\x0434\x0434\x0435\x0440\x0436\x043a\x0430 \x0438 \x043a\x043e\x043d\x0442\x0440\x043e\x043b\x044c \x0442\x043e\x043b\x043f\x044b.", RGB(0x7A,0x4A,0x4A), 80, 30, 160, 0 },
};

static const wchar_t* APP_TITLE = L"\x042f\x0412\x042c: \x0417\x0430\x0431\x044b\x0442\x044b\x0435 \x0411\x044b\x043b\x0438\x043d\x044b";
static const wchar_t* S_LOGO    = L"\x042f \x0412 \x042c";
static const wchar_t* S_SLOGAN  = L"\x0417\x0430\x0431\x044b\x0442\x044b\x0435 \x0411\x044b\x043b\x0438\x043d\x044b \x0437\x043e\x0432\x0443\x0442";
static const wchar_t* B_START   = L"\x041d\x0410\x0427\x0410\x0422\x042c \x0418\x0413\x0420\x0423";
static const wchar_t* B_LORE    = L"\x041f\x0420\x0415\x0414\x0410\x041d\x0418\x0415";
static const wchar_t* B_EXIT    = L"\x0412\x042b\x0425\x041e\x0414";
static const wchar_t* B_BACK    = L"\x041d\x0430\x0437\x0430\x0434";
static const wchar_t* B_CHOOSE  = L"\x0412\x042b\x0411\x0420\x0410\x0422\x042c \x0413\x0415\x0420\x041e\x042f";
static const wchar_t* B_NEED    = L"\x0421\x043d\x0430\x0447\x0430\x043b\x0430 \x0432\x044b\x0431\x0435\x0440\x0438 \x0433\x0435\x0440\x043e\x044f";
static const wchar_t* H_WARN    = L"\x0412\x0432\x0435\x0434\x0438 \x0438\x043c\x044f \x0433\x0435\x0440\x043e\x044f!";
static const wchar_t* B_OK      = L"\x041f\x041e\x041d\x042f\x0422\x041d\x041e";
static const wchar_t* LORE_TEXT = L"\x0414\x0430\x0432\x043d\x043e \x044d\x0442\x043e \x0431\x044b\x043b\x043e, \x0438\x043b\x044c \x0442\x043e\x043b\x044c\x043a\x043e \x0441\x043d\x0438\x0442\x0441\x044f?\n\x041a\x043e\x043b\x043e\x0434\x0435\x0446 \x0432\x0440\x0435\x043c\x0451\x043d \x043c\x0443\x0442\x0438\x043b \x0432\x043e\x0434\x0443, \x0438 \x0441\x0442\x0451\x043b\x0441\x044c\n\x043c\x0435\x0436\x0434\x0443 \x042f\x0432\x044c\x0435\x0439 \x0438 \x041d\x0430\x0432\x044c\x044e \x0442\x043e\x043d\x043a\x0430\x044f \x0433\x0440\x0430\x043d\x044c.\n\n\x0417\x0430\x0431\x044b\x0442\x044b \x0438\x043c\x0435\x043d\x0430 \x0431\x043e\x0433\x0430\x0442\x044b\x0440\x0435\x0439, \x043f\x043e\x0442\x0443\x0445\x043b\x0438\n\x043a\x043e\x0441\x0442\x0440\x044b \x0432 \x043f\x0443\x0441\x0442\x044b\x0445 \x0434\x0435\x0440\x0435\x0432\x043d\x044f\x0445, \x0430 \x0431\x044b\x043b\x0438\x043d\x044b\n\x0441\x043f\x044f\x0442 \x043d\x0430 \x0434\x043d\x0435 \x0447\x0451\x0440\x043d\x044b\x0445 \x043e\x0437\x0451\x0440.\n\n\x041d\x043e \x041d\x0430\x0432\x044c \x043d\x0435 \x0441\x043f\x0438\x0442. \x041e\x043d\x0430 \x043f\x043e\x0434\x0441\x044b\x043b\x0430\x0435\x0442 \x043d\x0435\x0436\x0438\x0442\x044c,\n\x043c\x043e\x0440\x043e\x0447\x0438\x0442 \x043b\x0435\x0441, \x043c\x0430\x043d\x0438\x0442 \x043a \x0441\x0435\x0431\x0435.\n\n\x0412\x0441\x0442\x0430\x0432\x0430\x0439, \x0431\x044b\x043b\x0438\x043d\x0443\x0448\x043a\x0430. \x041f\x043e\x043a\x0430 \x043f\x043e\x043c\x043d\x044f\x0442 \x2014 \x0436\x0438\x0432\x044b.";

/* --- Continue screen (profile found) --- */
static const wchar_t* H_CONT1   = L"\x041d\x0430\x0439\x0434\x0435\x043d \x043f\x0440\x043e\x0444\x0438\x043b\x044c \x0433\x0435\x0440\x043e\x044f:";
static const wchar_t* B_CONT    = L"\x041f\x0420\x041e\x0414\x041e\x041b\x0416\x0418\x0422\x042c \x0418\x0413\x0420\x0423";
static const wchar_t* B_NEW     = L"\x041d\x041e\x0412\x042b\x0419 \x0413\x0415\x0420\x041e\x0419";

/* --- World / village strings (stable names) --- */
static const wchar_t* CAT_NAME  = L"\x041a\x043e\x0442 \x0423\x0447\x0451\x043d\x044b\x0439"; /* Кот Учёный */
static const wchar_t* Q_TITLE   = L"\x0417\x0430\x0434\x0430\x043d\x0438\x0435:";           /* Задание: */
static const wchar_t* T_ACORN   = L"\x0416\x0435\x043b\x0443\x0434\x044c";                 /* Желудь */
static const wchar_t* T_OAK     = L"\x0414\x0443\x0431-\x043a\x0440\x0435\x0441\x0442";     /* Дуб-крест */
static const wchar_t* SAVE_TAG  = L"\x25CF \x0441\x043e\x0445\x0440\x0430\x043d\x0435\x043d\x043e"; /* сохранено */

/* v0.4 string table (generated by Prototype/gen_strings.py from RU source) */
#include "strings_gen.h"

/* ------------------------------- State ----------------------------------- */
static int  g_screen   = SCR_LAUNCH;
static int  g_selected = -1;
static HWND g_hWnd     = NULL;
static HWND g_editNick = NULL;
static HFONT g_fBig, g_fMed, g_fSmall, g_fTitle;

/* forward decls */
static void DrawFrameAt(HDC hdc, RECT r, COLORREF c);
static void DrawCatExtras(HDC hdc);
static void DrawVillageCatParts(HDC hdc);
static void DrawHero(HDC hdc);
static void PaintLaunch(HWND hwnd, HDC hdc);
static void PaintSelect(HWND hwnd, HDC hdc);
static void ShowDialogTop(const wchar_t* fmt, ...);
static void TalkSmith(HWND hwnd);
static void TalkMarya(HWND hwnd);
static void ChooseProfession(HWND hwnd, int idx);
static void DrawAbilityBar(HDC hdc);
static int  BlockedAt(int nx, int ny);
static void CastAbility(HWND hwnd, int slot);
static void SaveProfile(void);
static wchar_t q_buf[128];
static int  InvAdd(int id, int n);
static int  InvCount(int id);
static void InvRemove(int id, int n);
static void SetFocusNpc(int kind, int id, const wchar_t* name);
static void UpdateFocus(void);
static void QuestAdvanceCheck(void);
static void ShowDialogTop(const wchar_t* fmt, ...);
static void TalkSmith(HWND hwnd);
static void TalkMarya(HWND hwnd);
static void ChooseProfession(HWND hwnd, int idx);

/* Player / world state (server-authoritative model mirrored locally) */
static wchar_t g_nick[64] = L"";
static int  g_px = 320, g_py = 380;          /* player pos in client units */
static int  g_hpCur = 100, g_hpMax = 100;
static int  g_questStep = 0;                  /* 0 none,1 greet,2 acorns,3 return,4 done */
static int  g_acorns = 0;
static int  g_catTalked = 0;
static int  g_dialogShown = 0;                /* dialog box visible */
static ULONGLONG g_dialogUntil = 0;
static wchar_t g_dialogText[512];
static ULONGLONG g_lastSave = 0;
static ULONGLONG g_saveFlashUntil = 0;        /* show "saved" indicator briefly */

/* Mouse-to-walk destination (click where to go) */
static int g_walkDestSet = 0;
static int g_walkX = 0, g_walkY = 0;

/* Energy / buffs for the ability hotbar (keys 1..4) */
static int  g_energyCur = 60, g_energyMax = 60;
static ULONGLONG g_buffUntil = 0;             /* damage buff expiry */
static ULONGLONG g_lastRegen = 0;             /* passive energy regen tick */

/* Acorns under the oak (fixed positions, respawn per session only) */
typedef struct { int x, y, taken; } Acorn;
static Acorn g_acorns_arr[3] = { {262,196,0}, {352,214,0}, {300,252,0} };

/* ======================= v0.4: items, inventory, NPCs, quests ============ */
enum { ITEM_ACORN=1, ITEM_METAL, ITEM_CLOTH, ITEM_POTION, ITEM_AMULET,
       ITEM_BULAVA, ITEM_LUKO, ITEM_POSOH, ITEM_HEAVY, ITEM_LEATHER, ITEM_MANTLE };
enum { CAT_W=0, WARRIOR_W=1, HUNTER_W=2, MAGUS_W=3 };   /* weapon classes */
typedef struct { int id; const wchar_t* name; COLORREF col; int wcls, bonus; } ItemDef;
static ItemDef g_items[12];
#define NITEMS 12
static void InitItems(void)
{
    int k = 0;
    g_items[k++] = (ItemDef){ 0, NULL, RGB(0,0,0), 0, 0 };
    g_items[k++] = (ItemDef){ ITEM_ACORN,  IT_ACORN,  RGB(0xC8,0x8A,0x3E), 0, 0 };
    g_items[k++] = (ItemDef){ ITEM_METAL,  IT_METAL,  RGB(0x8A,0x8A,0x94), 0, 0 };
    g_items[k++] = (ItemDef){ ITEM_CLOTH,  IT_CLOTH,  RGB(0xE8,0xE0,0xC8), 0, 0 };
    g_items[k++] = (ItemDef){ ITEM_POTION, IT_POTION, RGB(0x4A,0xA0,0x60), 0, 0 };
    g_items[k++] = (ItemDef){ ITEM_AMULET, IT_AMULET, RGB(0xE0,0xB0,0x40), 0, 0 };
    g_items[k++] = (ItemDef){ ITEM_BULAVA, IT_BULAVA, RGB(0xB0,0x90,0x40), WARRIOR_W, 8 };
    g_items[k++] = (ItemDef){ ITEM_LUKO,   IT_LUKO,   RGB(0x7A,0x5A,0x30), HUNTER_W,  8 };
    g_items[k++] = (ItemDef){ ITEM_POSOH,  IT_POSOH,  RGB(0x6A,0x4A,0x8A), MAGUS_W,   8 };
    g_items[k++] = (ItemDef){ ITEM_HEAVY,  IT_HEAVY,  RGB(0x5A,0x6A,0x8A), 0, 10 };
    g_items[k++] = (ItemDef){ ITEM_LEATHER,IT_LEATHER,RGB(0x7A,0x5A,0x3A), 0, 6 };
    g_items[k++] = (ItemDef){ ITEM_MANTLE, IT_MANTLE, RGB(0x7A,0x4A,0x4A), 0, 4 };
}
#define NITEMS (int)(sizeof(g_items)/sizeof(g_items[0]))
static const ItemDef* Item(int id) { int i; for (i=1;i<NITEMS;i++) if (g_items[i].id==id) return &g_items[i]; return NULL; }

#define INV_CAP 12
typedef struct { int id, count; } Slot;
static Slot  g_inv[INV_CAP];
static int   g_equipW = 0, g_equipA = 0, g_equipR = 0;   /* item ids or 0 */
static int   g_invOpen = 0;
static int   g_level = 1, g_profBonus = 0;              /* profession bonus */
static int   g_youngster = 1;                           /* 1 = молодец, 0 = истый герой */
static int   g_quest = 0;                               /* see quest flow below */
static int   g_smithStage = 0, g_maryaStage = 0;        /* 0 none,1 got mat,2 crafting,3 done */
static ULONGLONG g_smithDoneAt = 0, g_maryaDoneAt = 0;
static int   g_focusKind = 0, g_focusId = 0;            /* 0 none,1 npc(id=cat/smith/marya idx),2 item,3 object */
static wchar_t g_focusName[64] = L"";
static wchar_t g_speaker[64] = L"";   /* who said the current line */

/* NPC positions */
#define SMITH_X 96
#define SMITH_Y 216
#define MARYA_X 548
#define MARYA_Y 214
#define SPOT_X  560
#define SPOT_Y  360

#define WORLD_TOP 96
#define OAK_X 300
#define OAK_Y 190
#define CAT_X 392
#define CAT_Y 236
#define PICK_R 26
#define TALK_R 46
#define WALK_SPEED 5      /* px per tick (tick = 50 ms) -> ~100 px/s */
#define NABILITY 4

/* ----------------------------- Abilities ---------------------------------- */
enum { AB_DMG = 0, AB_HEAL, AB_BUFF, AB_PICK };
typedef struct {
    const wchar_t* name;
    const wchar_t* tag;   /* short effect line for the bar */
    int cost;             /* energy */
    int power;
    ULONGLONG cd;         /* cooldown ms; <1000 => "basic attack", no cooldown */
    int kind;
    ULONGLONG cdUntil;    /* runtime only */
    ULONGLONG readyAt;    /* runtime only: when ability is ready again */
    ULONGLONG lastCast;   /* runtime only */
} Ability;
static Ability g_ab[NABILITY];

static void BuildAbilities(void)
{
    int i, dmg = 10;
    /* Hotbar follows the chosen profession; until then the hero is a
       "молодец" (starter) and uses the base set with lower damage. */
    for (i = 0; i < NABILITY; i++) { memset(&g_ab[i], 0, sizeof(Ability)); }
    g_ab[0].name = L"\x0423\x0434\x0430\x0440";            /* Удар (basic) */
    g_ab[0].tag  = L"-\x0416";                              /* -Ж */
    g_ab[0].kind = AB_DMG; g_ab[0].cost = 0; g_ab[0].cd = 400;
    g_ab[1].kind = AB_DMG; g_ab[1].cd = 8000;
    g_ab[2].name = L""; g_ab[2].kind = AB_HEAL; g_ab[2].cd = 15000;
    g_ab[3].name = L"\x0417\x043e\x0440\x044e";            /* Зорю */
    g_ab[3].tag  = L"+\x0416\x0435\x043b";                 /* +Жел */
    g_ab[3].kind = AB_PICK; g_ab[3].cost = 10; g_ab[3].power = 0; g_ab[3].cd = 3000;
    switch (g_selected) {
        case 0: /* Богатырь / Воин */
            dmg = 16;
            g_ab[1].name = L"\x041c\x0435\x0447\x044c";   /* Меч? use Могучий Удар */
            g_ab[1].name = L"\x041c\x043e\x0433\x0443\x0447\x0438\x0439 \x0423\x0434\x0430\x0440"; /* Могучий Удар */
            g_ab[1].tag = L"-24 \x043f\x043e \x0432\x0441\x0435\x043c";
            g_ab[1].cost = 20; g_ab[1].power = 24;
            g_ab[2].name = L"\x041a\x043b\x044f\x0442\x0432\x0430 \x0411\x043e\x0433\x0430"; /* Клятва Бога */
            g_ab[2].tag  = L"+36 \x0416";
            g_ab[2].cost = 25; g_ab[2].power = 36;
            break;
        case 1: /* Стрелок / Лучник */
            dmg = 20;
            g_ab[1].name = L"\x0422\x043e\x0447\x043d\x044b\x0439 \x0412\x044b\x0441\x0442\x0440\x0435\x043b"; /* Точный Выстрел */
            g_ab[1].tag  = L"-30";
            g_ab[1].cost = 15; g_ab[1].power = 30;
            g_ab[2].name = L"\x0412\x0435\x0442\x0435\x0440";  /* Ветер: buff +50% dmg */
            g_ab[2].tag  = L"+50% \x0443\x0440\x043e\x043d";
            g_ab[2].kind = AB_BUFF; g_ab[2].cost = 20; g_ab[2].power = 0; g_ab[2].cd = 20000;
            break;
        case 2: /* Волхв */
            dmg = 13;
            g_ab[1].name = L"\x041e\x0433\x043d\x0435\x043d\x044c"; /* Огонёк */
            g_ab[1].tag  = L"-26";
            g_ab[1].cost = 25; g_ab[1].power = 26;
            g_ab[2].name = L"\x0427\x0443\x0440\x0430";     /* Чур: heal */
            g_ab[2].tag  = L"+26 \x0416";
            g_ab[2].cost = 30; g_ab[2].power = 26;
            break;
        default: break;
    }
    /* equipment + profession bonuses ride on top of base damage */
    dmg += g_profBonus;
    if (g_equipW) dmg += Item(g_equipW)->bonus;
    if (g_equipA) dmg += Item(g_equipA)->bonus / 2;
    g_ab[0].power = dmg;
    {
        static wchar_t t0[8];
        swprintf(t0, 8, L"-%d", dmg);
        g_ab[0].tag = t0;
    }
}

/* ========================= v0.4: inventory logic ========================== */
static int InvAdd(int id, int n)
{
    int i;
    for (i = 0; i < INV_CAP; i++)
        if (g_inv[i].id == id && g_inv[i].count > 0) { g_inv[i].count += n; return 1; }
    for (i = 0; i < INV_CAP; i++)
        if (g_inv[i].id == 0) { g_inv[i].id = id; g_inv[i].count = n; return 1; }
    ShowDialogTop(D_FULL, L"");
    return 0;
}
static int InvCount(int id)
{
    int i;
    for (i = 0; i < INV_CAP; i++) if (g_inv[i].id == id) return g_inv[i].count;
    return 0;
}
static void InvRemove(int id, int n)
{
    int i;
    for (i = 0; i < INV_CAP; i++) {
        if (g_inv[i].id == id) {
            g_inv[i].count -= n;
            if (g_inv[i].count <= 0) { g_inv[i].id = 0; g_inv[i].count = 0; }
            return;
        }
    }
}
static int IsEquipped(int id) { return id && (g_equipW == id || g_equipA == id || g_equipR == id); }

/* equip toggle by item id; returns 1 if state changed */
static int ToggleEquip(HWND hwnd, int id)
{
    const ItemDef* d = Item(id);
    if (!d) return 0;
    if (IsEquipped(id)) {                        /* unequip -> back to bag */
        if (g_equipW == id) g_equipW = 0;
        if (g_equipA == id) g_equipA = 0;
        if (g_equipR == id) g_equipR = 0;
        InvAdd(id, 1);
        ShowDialogTop(D_UNEQ, d->name);
        BuildAbilities(); SaveProfile(); InvalidateRect(hwnd, NULL, FALSE);
        return 1;
    }
    if (d->wcls) {                               /* weapon slot */
        if (g_equipW) { if (!ToggleEquip(hwnd, g_equipW)) return 0; }
        InvRemove(id, 1); g_equipW = id;
        ShowDialogTop(D_EQUIPED, d->name, d->bonus);
        BuildAbilities(); SaveProfile(); InvalidateRect(hwnd, NULL, FALSE);
        return 1;
    }
    if (id >= ITEM_HEAVY && id <= ITEM_MANTLE) {      /* armor slot */
        if (g_equipA) { if (!ToggleEquip(hwnd, g_equipA)) return 0; }
        InvRemove(id, 1); g_equipA = id;
        ShowDialogTop(D_EQUIPED, d->name, d->bonus);
        BuildAbilities(); SaveProfile(); InvalidateRect(hwnd, NULL, FALSE);
        return 1;
    }
    if (id == ITEM_AMULET) {
        if (g_equipR) { if (!ToggleEquip(hwnd, g_equipR)) return 0; }
        InvRemove(id, 1); g_equipR = id;
        ShowDialogTop(D_EQUIPED, d->name, 2);
        BuildAbilities(); SaveProfile(); InvalidateRect(hwnd, NULL, FALSE);
        return 1;
    }
    ShowDialogTop(D_NOT_EQUIP);
    return 0;
}

/* click on inventory grid -> item index or -1 (rect set in DrawInventory) */
static RECT g_invRects[INV_CAP];
static int  g_invGridN = 0;

/* --------------------------- File DB (real time) ------------------------- */
static void ProfilePathW(wchar_t* out, size_t cch)
{
    wchar_t* dot;
    GetModuleFileNameW(NULL, out, (DWORD)cch);
    dot = wcsrchr(out, L'.');
    if (dot) wcscpy(dot, L"_profile.json");
    else     wcscat(out, L"_profile.json");
}

/* Atomic save: write temp then MoveFileEx replace => never corrupts on crash */
static void SaveProfile(void)
{
    wchar_t wpath[MAX_PATH], wtmp[MAX_PATH];
    if (g_editNick && g_screen == SCR_SELECT)
        GetWindowTextW(g_editNick, g_nick, 63); /* keep live nickname */
    char apath[MAX_PATH*3], atmp[MAX_PATH*3], nutf[256];
    FILE* f;
    time_t t = time(NULL);
    struct tm tmv;
    char stamp[32];

    ProfilePathW(wpath, MAX_PATH);
    lstrcpynW(wtmp, wpath, MAX_PATH);
    wcscat(wtmp, L".tmp");

    WideCharToMultiByte(CP_UTF8, 0, wpath, -1, apath, sizeof(apath), NULL, NULL);
    WideCharToMultiByte(CP_UTF8, 0, wtmp,  -1, atmp,  sizeof(atmp),  NULL, NULL);
    WideCharToMultiByte(CP_UTF8, 0, g_nick, -1, nutf, sizeof(nutf), NULL, NULL);

#ifdef _MSC_VER
    localtime_s(&tmv, &t);
#else
    tmv = *localtime(&t);
#endif
    strftime(stamp, sizeof(stamp), "%Y-%m-%dT%H:%M:%S", &tmv);

    f = fopen(atmp, "w");
    if (!f) return;
    /* v0.4: inventory + equipment + quest progress serialized too */
    {
        char invJson[512]; int o = 0, i;
        o += snprintf(invJson + o, sizeof(invJson) - o, "[");
        for (i = 0; i < INV_CAP; i++)
            o += snprintf(invJson + o, sizeof(invJson) - o, "%s%d:%d",
                          i ? "," : "", g_inv[i].id, g_inv[i].count);
        snprintf(invJson + o, sizeof(invJson) - o, "]");
        fprintf(f,
            "{\n"
            "  \"version\": 4,\n"
            "  \"updatedAt\": \"%s\",\n"
            "  \"nickname\": \"%s\",\n"
            "  \"classId\": %d,\n"
            "  \"hp\": %d,\n"
            "  \"hpMax\": %d,\n"
            "  \"energy\": %d,\n"
            "  \"level\": %d,\n"
            "  \"profBonus\": %d,\n"
            "  \"youngster\": %d,\n"
            "  \"pos\": { \"x\": %d, \"y\": %d },\n"
            "  \"quest\": { \"step\": %d, \"q\": %d, \"acorns\": %d, \"catTalked\": %s, \"smith\": %d, \"marya\": %d },\n"
            "  \"equip\": { \"w\": %d, \"a\": %d, \"r\": %d },\n"
            "  \"inventory\": %s,\n"
            "  \"acornTaken\": [%d, %d, %d]\n"
            "}\n",
            stamp, nutf, g_selected, g_hpCur, g_hpMax, g_energyCur,
            g_level, g_profBonus, g_youngster, g_px, g_py,
            g_questStep, g_quest, g_acorns, g_catTalked ? "true" : "false",
            g_smithStage, g_maryaStage,
            g_equipW, g_equipA, g_equipR, invJson,
            g_acorns_arr[0].taken, g_acorns_arr[1].taken, g_acorns_arr[2].taken);
    }
    fclose(f);

    /* atomic replace: MoveFileEx(REPLACE_EXISTING) without prior delete */
    if (!MoveFileExA(atmp, apath, MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH)) {
        remove(atmp);
        rename(atmp, apath);
    }
    g_lastSave = GetTickCount64();
    g_saveFlashUntil = g_lastSave + 1500;
}

/* Minimal JSON reader for our own format (tolerant of key order) */
static int JsonGetInt(const char* js, const char* key, int def)
{
    char pat[64];
    const char* p;
    snprintf(pat, sizeof(pat), "\"%s\"", key);
    p = strstr(js, pat);
    if (!p) return def;
    p += strlen(pat);
    p = strchr(p, ':');
    if (!p) return def;
    return atoi(p + 1);
}
static void JsonGetStr(const char* js, const char* key, wchar_t* out, size_t cch, const wchar_t* def)
{
    char pat[64], buf[256];
    const char* p, *s, *e;
    int n;
    snprintf(pat, sizeof(pat), "\"%s\"", key);
    p = strstr(js, pat);
    wcscpy(out, def);
    if (!p) return;
    p = strchr(p + strlen(pat), '"');
    if (!p) return;
    s = p + 1;
    e = strchr(s, '"');
    if (!e) return;
    n = (int)(e - s);
    if (n > 250) n = 250;
    memcpy(buf, s, n);
    buf[n] = 0;
    MultiByteToWideChar(CP_UTF8, 0, buf, -1, out, (int)cch);
}

static int LoadProfile(void) /* returns 1 if a valid profile was loaded */
{
    wchar_t wpath[MAX_PATH];
    char apath[MAX_PATH*3];
    FILE* f;
    long sz;
    char* buf;
    int ok = 0, i;

    ProfilePathW(wpath, MAX_PATH);
    WideCharToMultiByte(CP_UTF8, 0, wpath, -1, apath, sizeof(apath), NULL, NULL);
    f = fopen(apath, "rb");
    if (!f) return 0;
    fseek(f, 0, SEEK_END); sz = ftell(f); fseek(f, 0, SEEK_SET);
    if (sz <= 0 || sz > 65536) { fclose(f); return 0; }
    buf = (char*)malloc(sz + 1);
    if (!buf) { fclose(f); return 0; }
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return 0; }
    buf[sz] = 0;
    fclose(f);

    if (strstr(buf, "\"classId\"")) {
        g_selected   = JsonGetInt(buf, "classId", -1);
        g_hpMax      = JsonGetInt(buf, "hpMax", g_class[g_selected >= 0 && g_selected < NCLASS ? g_selected : 0].hp);
        g_hpCur      = JsonGetInt(buf, "hp", g_hpMax);
        g_energyMax  = (g_selected >= 0 && g_selected < NCLASS) ? g_class[g_selected].energy : 60;
        g_energyCur  = JsonGetInt(buf, "energy", g_energyMax);
        if (g_energyCur > g_energyMax) g_energyCur = g_energyMax;
        g_level      = JsonGetInt(buf, "level", 1);
        g_profBonus  = JsonGetInt(buf, "profBonus", 0);
        g_youngster  = JsonGetInt(buf, "youngster", 1);
        g_px         = JsonGetInt(buf, "x", 320);
        g_py         = JsonGetInt(buf, "y", 380);
        g_questStep  = JsonGetInt(buf, "step", 0);
        g_quest      = JsonGetInt(buf, "q", 0);
        g_acorns     = JsonGetInt(buf, "acorns", 0);
        g_smithStage = JsonGetInt(buf, "smith", 0);
        g_maryaStage = JsonGetInt(buf, "marya", 0);
        g_catTalked  = strstr(buf, "\"catTalked\": true") ? 1 : 0;
        for (i = 0; i < 3; i++) g_acorns_arr[i].taken = (i < g_acorns) ? 1 : 0;
        /* equipment */
        g_equipW = JsonGetInt(buf, "w", 0);
        g_equipA = JsonGetInt(buf, "a", 0);
        g_equipR = JsonGetInt(buf, "r", 0);
        /* inventory: "inventory": [id:count,...] — tolerant manual parse */
        memset(g_inv, 0, sizeof(g_inv));
        { const char* p = strstr(buf, "\"inventory\"");
          if (p) {
            int slot = 0;
            p = strchr(p, '[');
            if (p) {
                p++;
                while (*p && *p != ']' && slot < INV_CAP) {
                    int id = (int)strtol(p, (char**)&p, 10), cnt = 0;
                    if (*p == ':') { cnt = (int)strtol(p + 1, (char**)&p, 10); }
                    if (id > 0) { g_inv[slot].id = id; g_inv[slot].count = cnt; slot++; }
                    while (*p == ',' || *p == ' ' || *p == '\n') p++;
                    if (!isdigit((unsigned char)*p) && *p != '-') break;
                }
            }
          } }
        JsonGetStr(buf, "nickname", g_nick, 64, L"");
        if (g_selected >= 0 && g_selected < NCLASS && wcslen(g_nick) > 0) ok = 1;
    }
    free(buf);
    return ok;
}

/* ------------------------------ Rendering -------------------------------- */
static void DrawFrame(HDC hdc, RECT r, COLORREF c)
{
    HPEN pen = CreatePen(PS_SOLID, 2, c);
    HPEN old = (HPEN)SelectObject(hdc, pen);
    HBRUSH ob = (HBRUSH)SelectObject(hdc, GetStockObject(NULL_BRUSH));
    Rectangle(hdc, r.left, r.top, r.right, r.bottom);
    SelectObject(hdc, old);
    SelectObject(hdc, ob);
    DeleteObject(pen);
}

static void TextC(HDC hdc, int x, int y, const wchar_t* s, COLORREF c, HFONT f, int center)
{
    HFONT old = (HFONT)SelectObject(hdc, f);
    SetTextColor(hdc, c);
    SetBkMode(hdc, TRANSPARENT);
    if (center) {
        SIZE sz; GetTextExtentPoint32W(hdc, s, (int)wcslen(s), &sz);
        TextOutW(hdc, x - sz.cx / 2, y, s, (int)wcslen(s));
    } else {
        TextOutW(hdc, x, y, s, (int)wcslen(s));
    }
    SelectObject(hdc, old);
}

static void FillCircle(HDC hdc, int cx, int cy, int r, COLORREF c)
{
    HBRUSH b = CreateSolidBrush(c);
    HPEN p = (HPEN)GetStockObject(NULL_PEN);
    HPEN op = (HPEN)SelectObject(hdc, p);
    HBRUSH ob = (HBRUSH)SelectObject(hdc, b);
    Ellipse(hdc, cx - r, cy - r, cx + r, cy + r);
    SelectObject(hdc, op);
    SelectObject(hdc, ob);
    DeleteObject(b);
}

static void FillEllipse(HDC hdc, int cx, int cy, int rx, int ry, COLORREF c)
{
    HBRUSH b = CreateSolidBrush(c);
    HPEN op = (HPEN)SelectObject(hdc, (HPEN)GetStockObject(NULL_PEN));
    HBRUSH ob = (HBRUSH)SelectObject(hdc, b);
    Ellipse(hdc, cx - rx, cy - ry, cx + rx, cy + ry);
    SelectObject(hdc, op);
    SelectObject(hdc, ob);
    DeleteObject(b);
}

static void RectFill(HDC hdc, int x, int y, int w, int h, COLORREF c)
{
    HBRUSH b = CreateSolidBrush(c);
    RECT r = { x, y, x + w, y + h };
    FillRect(hdc, &r, b);
    DeleteObject(b);
}

/* left/right aligned text (center flag variant is TextC) */
static void TextL(HDC hdc, int x, int y, const wchar_t* s, COLORREF c, HFONT f)
{
    TextC(hdc, x, y, s, c, f, 0);
}
static void TextR(HDC hdc, int right, int y, const wchar_t* s, COLORREF c, HFONT f)
{
    SIZE sz; HFONT old = (HFONT)SelectObject(hdc, f);
    SetBkMode(hdc, TRANSPARENT);
    GetTextExtentPoint32W(hdc, s, (int)wcslen(s), &sz);
    SelectObject(hdc, old);
    TextC(hdc, right - sz.cx, y, s, c, f, 0);
}

/* 3D-ish horizontal bar: dark trough + colored fill + light top edge */
static void Bar3D(HDC hdc, int x, int y, int w, int h, double frac, COLORREF col)
{
    RECT tr = { x, y, x + w, y + h };
    HBRUSH b;
    if (frac < 0) frac = 0; if (frac > 1) frac = 1;
    b = CreateSolidBrush(RGB(0x0A,0x0C,0x14));
    FillRect(hdc, &tr, b); DeleteObject(b);
    { RECT fr = tr; fr.right = x + (int)(w * frac);
      b = CreateSolidBrush(col);
      FillRect(hdc, &fr, b); DeleteObject(b);
      /* glossy top half */
      { RECT gl = fr; gl.bottom = y + h/2;
        b = CreateSolidBrush(RGB(
            min(255, (int)GetRValue(col)+40),
            min(255, (int)GetGValue(col)+40),
            min(255, (int)GetBValue(col)+40)));
        FillRect(hdc, &gl, b); DeleteObject(b); } }
    DrawFrameAt(hdc, tr, RGB(0x55,0x5A,0x6A));
}

static void Line(HDC hdc, int x1, int y1, int x2, int y2, COLORREF c, int wide)
{
    HPEN p = CreatePen(PS_SOLID, wide, c);
    HPEN o = (HPEN)SelectObject(hdc, p);
    MoveToEx(hdc, x1, y1, NULL);
    LineTo(hdc, x2, y2);
    SelectObject(hdc, o);
    DeleteObject(p);
}

/* ------------ Village drawing (logic-free, pure visual layer) ------------- */
static void DrawVillageCatParts(HDC hdc)
{
    /* body */
    FillEllipse(hdc, CAT_X, CAT_Y + 8, 13, 16, RGB(0x59,0x59,0x63));
    /* head */
    FillCircle(hdc, CAT_X, CAT_Y - 14, 11, RGB(0x66,0x66,0x70));
    /* tail */
    Line(hdc, CAT_X + 12, CAT_Y + 16, CAT_X + 22, CAT_Y - 2, RGB(0x59,0x59,0x63), 4);
    DrawCatExtras(hdc);
}

static void DrawCatExtras(HDC hdc)
{
    /* ears */
    HBRUSH b = CreateSolidBrush(RGB(0x66,0x66,0x70));
    HPEN   p = (HPEN)GetStockObject(NULL_PEN);
    HPEN   op = (HPEN)SelectObject(hdc, p);
    HBRUSH ob = (HBRUSH)SelectObject(hdc, b);
    POINT e1[3] = {{CAT_X-11,CAT_Y-20},{CAT_X-7,CAT_Y-32},{CAT_X-1,CAT_Y-22}};
    POINT e2[3] = {{CAT_X+11,CAT_Y-20},{CAT_X+7,CAT_Y-32},{CAT_X+1,CAT_Y-22}};
    Polygon(hdc, e1, 3);
    Polygon(hdc, e2, 3);
    SelectObject(hdc, ob); DeleteObject(b); SelectObject(hdc, op);

    /* eyes */
    FillCircle(hdc, CAT_X - 4, CAT_Y - 15, 2, RGB(0xFF,0xE9,0x7A));
    FillCircle(hdc, CAT_X + 4, CAT_Y - 15, 2, RGB(0xFF,0xE9,0x7A));

    /* spectacles — he is a scholar */
    HPEN gp = CreatePen(PS_SOLID, 1, RGB(0xE8,0xE0,0xB0));
    HPEN go = (HPEN)SelectObject(hdc, gp);
    SelectObject(hdc, GetStockObject(NULL_BRUSH));
    Ellipse(hdc, CAT_X - 8, CAT_Y - 19, CAT_X - 1, CAT_Y - 12);
    Ellipse(hdc, CAT_X + 1, CAT_Y - 19, CAT_X + 8, CAT_Y - 12);
    Line(hdc, CAT_X - 1, CAT_Y - 16, CAT_X + 1, CAT_Y - 16, RGB(0xE8,0xE0,0xB0), 1);
    SelectObject(hdc, go); DeleteObject(gp);

    /* little scroll in paws */
    RectFill(hdc, CAT_X - 6, CAT_Y + 6, 12, 8, RGB(0xF2,0xE7,0xC8));
    Line(hdc, CAT_X - 6, CAT_Y + 6, CAT_X - 6, CAT_Y + 14, RGB(0xB0,0x9A,0x60), 2);
    Line(hdc, CAT_X + 6, CAT_Y + 6, CAT_X + 6, CAT_Y + 14, RGB(0xB0,0x9A,0x60), 2);

    TextC(hdc, CAT_X, CAT_Y + 30, CAT_NAME, RGB(0xFF,0xF3,0xC0), g_fSmall, 1);
}

static void DrawHero(HDC hdc)
{
    COLORREF col = (g_selected >= 0 && g_selected < NCLASS) ? g_class[g_selected].color : RGB(60,60,120);
    /* shadow */
    FillEllipse(hdc, g_px, g_py + 14, 10, 4, RGB(0x40,0x55,0x35));
    /* body */
    FillEllipse(hdc, g_px, g_py + 2, 8, 11, col);
    /* head */
    FillCircle(hdc, g_px, g_py - 14, 7, RGB(0xE8,0xC8,0x9A));
    TextC(hdc, g_px, g_py + 20, g_nick, RGB(0xFF,0xFF,0xFF), g_fSmall, 1);
}

static void DrawDialogBox(HDC hdc)
{
    RECT r = { 24, 356, 616, 448 };
    HPEN pen;
    if (!g_dialogShown) return;
    pen = CreatePen(PS_SOLID, 2, RGB(0xE8,0xD8,0x9A));
    SelectObject(hdc, pen);
    { HBRUSH b = CreateSolidBrush(RGB(0x24,0x1E,0x14));
      HBRUSH ob=(HBRUSH)SelectObject(hdc,b);
      Rectangle(hdc, r.left, r.top, r.right, r.bottom);
      SelectObject(hdc, ob); DeleteObject(b); }
    DeleteObject(pen);
    TextC(hdc, r.left + 12, r.top + 8, CAT_NAME, RGB(0xFF,0xE9,0x7A), g_fMed, 0);
    {
        /* naive word-wrap into 2 lines */
        HDC mdc = hdc; HFONT of = SelectObject(mdc, g_fSmall);
        wchar_t line1[256] = L"", line2[256] = L"";
        const wchar_t* s = g_dialogText; int w, maxw = 560, cur = 0; int l2 = 0;
        const wchar_t* start = s;
        while (*s) {
            const wchar_t* sp = wcschr(s, L' ');
            int len = sp ? (int)(sp - s) : (int)wcslen(s);
            SIZE sz; GetTextExtentPoint32W(mdc, start, (int)(s + len - start), &sz);
            if (sz.cx > maxw) {
                if (!l2) { wcsncpy(line1, start, s - start); line1[s-start]=0; l2 = 1; }
                start = s;
            }
            s += len; if (*s == L' ') s++;
            (void)cur; (void)w;
        }
        if (l2) { SIZE sz; GetTextExtentPoint32W(mdc, start, (int)wcslen(start), &sz);
                  wcsncpy(line2, start, 255); line2[255]=0; }
        else    { wcsncpy(line1, start, 255); line1[255]=0; }
        SelectObject(mdc, of);
        TextC(hdc, r.left + 12, r.top + 30, line1, RGB(0xF0,0xEA,0xD0), g_fSmall, 0);
        if (line2[0]) TextC(hdc, r.left + 12, r.top + 48, line2, RGB(0xF0,0xEA,0xD0), g_fSmall, 0);
    }
    TextC(hdc, r.right - 120, r.bottom - 20, L"[E]/\x041a\x043b\x0438\x043a \x2014 \x0434\x0430\x043b\x044c\x0448\x0435", RGB(0xB0,0xA8,0x88), g_fSmall, 0);
}

static void DrawFrameAt(HDC hdc, RECT r, COLORREF c);

/* --- HUD: player info panel (top-left) ----------------------------------- */
static void PaintPlayerPanel(HDC hdc)
{
    RECT r = { 10, 10, 250, 96 };
    wchar_t b[128];
    HBRUSH br;
    HPEN pen;
    br = CreateSolidBrush(RGB(0x14,0x18,0x26));
    FillRect(hdc, &r, br); DeleteObject(br);
    pen = CreatePen(PS_SOLID, 2, RGB(0xC8,0x9A,0x3E));
    { HPEN o = (HPEN)SelectObject(hdc, pen);
      SelectObject(hdc, GetStockObject(NULL_BRUSH));
      Rectangle(hdc, r.left, r.top, r.right, r.bottom);
      SelectObject(hdc, o); }
    DeleteObject(pen);
    /* name + level */
    if (g_youngster) swprintf(b, 128, L"%ls \x2014 \x043c\x043e\x043b\x043e\x0434\x0435\x0446", g_nick[0]?g_nick:L"???");
    else             swprintf(b, 128, L"%ls \x2014 %d \x0443\x0440.", g_nick[0]?g_nick:L"???", g_level);
    TextL(hdc, 18, 14, b, RGB(0xFF,0xE9,0x7A), g_fSmall);
    /* HP bar */
    Bar3D(hdc, 18, 36, 224, 14, (double)g_hpCur / (g_hpMax?g_hpMax:1), RGB(0xB0,0x30,0x30));
    swprintf(b, 128, L"\x0416:%d/%d", g_hpCur, g_hpMax);
    TextL(hdc, 22, 36, b, RGB(0xFF,0xFF,0xFF), g_fSmall);
    /* Energy bar */
    Bar3D(hdc, 18, 56, 224, 14, (double)g_energyCur / (g_energyMax?g_energyMax:1), RGB(0x30,0x60,0xC0));
    swprintf(b, 128, L"\x042d:%d/%d", g_energyCur, g_energyMax);
    TextL(hdc, 22, 56, b, RGB(0xFF,0xFF,0xFF), g_fSmall);
    /* acorns counter */
    swprintf(b, 128, L"\x0416\x0435\x043b\x0443\x0434\x0438: %d/3", g_acorns);
    TextL(hdc, 18, 76, b, RGB(0xC8,0x8A,0x3E), g_fSmall);
}

/* --- Focus info window (top-center) -------------------------------------- */
static void PaintFocusInfo(HDC hdc)
{
    RECT r = { WIN_W/2 - 130, 10, WIN_W/2 + 130, 40 };
    wchar_t b[128];
    HBRUSH br = CreateSolidBrush(RGB(0x10,0x16,0x22));
    FillRect(hdc, &r, br); DeleteObject(br);
    DrawFrameAt(hdc, r, RGB(0x6A,0x7A,0x9A));
    if (!g_focusKind) {
        TextC(hdc, WIN_W/2, 16, FOCUS_NONE, RGB(0x7A,0x86,0x9A), g_fSmall, 1);
        return;
    }
    switch (g_focusKind) {
        case 1: /* npc */
            swprintf(b, 128, D_FOCUS_NPC, g_focusName); break;
        case 2: /* item on ground */
            swprintf(b, 128, D_FOCUS_ITEM, g_focusName); break;
        default:
            if (g_focusId == 1) lstrcpynW(b, D_FOCUS_SPOT, 128);
            else                lstrcpynW(b, D_FOCUS_OAK, 128);
            break;
    }
    TextC(hdc, WIN_W/2, 16, b, RGB(0xE8,0xE0,0xC8), g_fSmall, 1);
}

/* --- Inventory panel (left side, Tab toggle) ------------------------------ */
static void PaintInventory(HDC hdc)
{
    int x0 = 10, y0 = 110, cell = 40, cols = 3, i, n = 0;
    RECT r = { x0, y0, x0 + cols*cell + 10, y0 + ((INV_CAP + cols - 1)/cols)*cell + 34 };
    HBRUSH br;
    g_invGridN = 0;
    if (!g_invOpen) return;
    br = CreateSolidBrush(RGB(0x12,0x16,0x24));
    FillRect(hdc, &r, br); DeleteObject(br);
    DrawFrameAt(hdc, r, RGB(0xC8,0x9A,0x3E));
    TextL(hdc, x0 + 8, y0 + 4, INV_TITLE, RGB(0xE8,0xC8,0x5A), g_fSmall);
    /* slots */
    for (i = 0; i < INV_CAP; i++) {
        int cx = x0 + 5 + (i % cols) * cell;
        int cy = y0 + 26 + (i / cols) * cell;
        RECT sr = { cx, cy, cx + cell - 4, cy + cell - 4 };
        wchar_t b[48];
        br = CreateSolidBrush(RGB(0x1C,0x22,0x34));
        FillRect(hdc, &sr, br); DeleteObject(br);
        DrawFrameAt(hdc, sr, RGB(0x3A,0x44,0x5C));
        g_invRects[g_invGridN++] = sr;
        if (g_inv[i].id) {
            const ItemDef* d = Item(g_inv[i].id);
            RECT ir = { cx + 8, cy + 8, cx + cell - 12, cy + cell - 12 };
            br = CreateSolidBrush(d->col);
            FillRect(hdc, &ir, br); DeleteObject(br);
            if (d->wcls || (d->id >= ITEM_HEAVY && d->id <= ITEM_MANTLE) || d->id == ITEM_AMULET)
                DrawFrameAt(hdc, ir, RGB(0xFF,0xE9,0x7A));
            swprintf(b, 48, L"%d", g_inv[i].count);
            TextR(hdc, cx + cell - 8, cy + cell - 20, b, RGB(0xFF,0xFF,0xFF), g_fSmall);
        }
    }
    /* equipped section */
    {
        int ey = y0 + ((INV_CAP + cols - 1)/cols)*cell + 34;
        {
            int k;
            const wchar_t* labels[3] = { SLOT_W, SLOT_A, SLOT_R };
            int ids[3] = { g_equipW, g_equipA, g_equipR };
            for (k = 0; k < 3; k++) {
                RECT er = { x0 + 5, ey + k*30, x0 + cols*cell + 5, ey + k*30 + 28 };
                wchar_t b[64];
                br = CreateSolidBrush(RGB(0x18,0x1E,0x2E));
                FillRect(hdc, &er, br); DeleteObject(br);
                DrawFrameAt(hdc, er, RGB(0x4A,0x8A,0x5A));
                if (ids[k]) swprintf(b, 64, L"%ls: %ls \x2713", labels[k], Item(ids[k])->name);
                else        swprintf(b, 64, L"%ls: \x2014", labels[k]);
                TextL(hdc, er.left + 6, er.top + 6, b,
                      ids[k] ? RGB(0x9A,0xE0,0x9A) : RGB(0x7A,0x86,0x9A), g_fSmall);
            }
        }
    }
}

/* --- Ability bar: centered at the bottom ---------------------------------- */
static void PaintAbilityBar(HDC hdc)
{
    int bw = 64, gap = 8, total = NABILITY*bw + (NABILITY-1)*gap;
    int x = WIN_W/2 - total/2, y = WIN_H - 74;
    int i;
    ULONGLONG now = GetTickCount64();
    for (i = 0; i < NABILITY; i++) {
        Ability* a = &g_ab[i];
        RECT r = { x + i*(bw+gap), y, x + i*(bw+gap) + bw, y + bw };
        wchar_t b[64];
        double cdLeft = (a->readyAt > now) ? (double)(a->readyAt - now)/a->cd : 0.0;
        HBRUSH br = CreateSolidBrush(RGB(0x18,0x1C,0x2A));
        FillRect(hdc, &r, br); DeleteObject(br);
        DrawFrameAt(hdc, r, RGB(0xC8,0x9A,0x3E));
        swprintf(b, 64, L"%d", i+1);
        TextL(hdc, r.left + 4, r.top + 2, b, RGB(0xE8,0xC8,0x5A), g_fSmall);
        if (a->tag[0]) {
            swprintf(b, 64, L"%ls", a->tag);
            TextC(hdc, (r.left+r.right)/2, r.top + 22, b, RGB(0xFF,0xFF,0xFF), g_fSmall, 1);
        }
        if (cdLeft > 0.0) {
            HBRUSH dim = CreateSolidBrush(RGB(0x08,0x0A,0x10));
            RECT dr = r; dr.top = r.top + (LONG)((1.0 - cdLeft) * (r.bottom - r.top));
            FillRect(hdc, &dr, dim); DeleteObject(dim);
        }
        if (g_energyCur < a->cost) {
            HPEN p = CreatePen(PS_SOLID, 2, RGB(0x60,0x60,0x60));
            HPEN o = (HPEN)SelectObject(hdc, p);
            SelectObject(hdc, GetStockObject(NULL_BRUSH));
            Rectangle(hdc, r.left, r.top, r.right, r.bottom);
            SelectObject(hdc, o); DeleteObject(p);
        }
    }
}

/* --- Dialog window: right side, vertically centered ----------------------- */
static void PaintDialogBox(HDC hdc)
{
    RECT r = { WIN_W - 330, WIN_H/2 - 90, WIN_W - 14, WIN_H/2 + 90 };
    HBRUSH br;
    if (!g_dialogShown) return;
    br = CreateSolidBrush(RGB(0x14,0x18,0x28));
    FillRect(hdc, &r, br); DeleteObject(br);
    DrawFrameAt(hdc, r, RGB(0xE8,0xC8,0x5A));
    TextL(hdc, r.left + 12, r.top + 8,
          g_speaker[0] ? g_speaker : CAT_NAME, RGB(0xE8,0xC8,0x5A), g_fMed);
    TextL(hdc, r.left + 12, r.top + 34, g_dialogText, RGB(0xF0,0xF0,0xF0), g_fSmall);
}

static void PaintWorld(HDC hdc)
{
    HPEN pen; HBRUSH br; RECT r; int i;
    wchar_t b[160];
    /* sky + ground */
    RectFill(hdc, 0, 0, WIN_W, WIN_H, RGB(0x14,0x18,0x26));
    RectFill(hdc, 0, WORLD_TOP, WIN_W, WIN_H - WORLD_TOP, RGB(0x1B,0x2A,0x1E));
    /* fence line */
    pen = CreatePen(PS_SOLID, 2, RGB(0x6A,0x5A,0x3A));
    { HPEN o = (HPEN)SelectObject(hdc, pen);
      MoveToEx(hdc, 14, WORLD_TOP - 6, NULL); LineTo(hdc, WIN_W - 14, WORLD_TOP - 6);
      for (i = 14; i < WIN_W - 14; i += 26) { MoveToEx(hdc, i, WORLD_TOP - 14, NULL); LineTo(hdc, i, WORLD_TOP + 2); }
      SelectObject(hdc, o); }
    DeleteObject(pen);
    /* road */
    RectFill(hdc, 0, 250, WIN_W, 60, RGB(0x3A,0x34,0x2A));
    /* huts: smith (left) and marya (right) */
    for (i = 0; i < 2; i++) {
        int hx = i == 0 ? SMITH_X - 44 : MARYA_X - 44;
        RECT hr = { hx, 120, hx + 88, 200 };
        br = CreateSolidBrush(RGB(0x6A,0x4A,0x2A));
        FillRect(hdc, &hr, br); DeleteObject(br);
        pen = CreatePen(PS_SOLID, 2, RGB(0x3A,0x2A,0x1A));
        { HPEN o = (HPEN)SelectObject(hdc, pen);
          SelectObject(hdc, GetStockObject(NULL_BRUSH));
          Rectangle(hdc, hr.left, hr.top, hr.right, hr.bottom);
          MoveToEx(hdc, hr.left, hr.top, NULL); LineTo(hdc, (hr.left+hr.right)/2, hr.top - 24);
          LineTo(hdc, hr.right, hr.top);
          SelectObject(hdc, o); }
        DeleteObject(pen);
        br = CreateSolidBrush(RGB(0x2A,0x22,0x14));
        { RECT door = { (hr.left+hr.right)/2 - 10, hr.bottom - 40, (hr.left+hr.right)/2 + 10, hr.bottom };
          FillRect(hdc, &door, br); }
        DeleteObject(br);
        TextC(hdc, (hr.left+hr.right)/2, hr.bottom + 4,
              i == 0 ? NPC_SMITH : NPC_MARYA, RGB(0xC8,0xC8,0xD8), g_fSmall, 1);
    }
    /* oak */
    br = CreateSolidBrush(RGB(0x5A,0x3A,0x20));
    { RECT trunk = { OAK_X - 12, OAK_Y + 10, OAK_X + 12, OAK_Y + 60 }; FillRect(hdc, &trunk, br); }
    DeleteObject(br);
    FillEllipse(hdc, OAK_X, OAK_Y - 14, 52, 38, RGB(0x2A,0x5A,0x2A));
    TextC(hdc, OAK_X, OAK_Y + 62, T_OAK, RGB(0xC8,0xC8,0xD8), g_fSmall, 1);
    /* dark grove spot */
    FillEllipse(hdc, SPOT_X, SPOT_Y, 40, 26, RGB(0x14,0x20,0x18));
    TextC(hdc, SPOT_X, SPOT_Y - 4, T_SPOT, RGB(0x7A,0x8A,0x7A), g_fSmall, 1);
    /* acorns: small nut with cap (matches the IT_ACORN icon color) */
    for (i = 0; i < 3; i++) {
        if (g_acorns_arr[i].taken) continue;
        FillCircle(hdc, g_acorns_arr[i].x, g_acorns_arr[i].y, 6, RGB(0xC8,0x8A,0x3E));
        FillEllipse(hdc, g_acorns_arr[i].x, g_acorns_arr[i].y - 5, 7, 4, RGB(0x6B,0x4A,0x24));
    }
    /* cat body + spectacles + scroll (Kot Ucheny) */
    DrawVillageCatParts(hdc);
    /* hero: head, class-colored body, nickname below */
    DrawHero(hdc);
    /* focus ring around focused entity */
    if (g_focusKind == 1) {
        int fx = g_focusId == 0 ? CAT_X : g_focusId == 1 ? SMITH_X : MARYA_X;
        int fy = g_focusId == 0 ? CAT_Y : g_focusId == 1 ? SMITH_Y + 30 : MARYA_Y + 30;
        HPEN fp = CreatePen(PS_SOLID, 2, RGB(0xFF,0xE9,0x7A));
        HPEN fo = (HPEN)SelectObject(hdc, fp);
        SelectObject(hdc, GetStockObject(NULL_BRUSH));
        Ellipse(hdc, fx - 26, fy - 24, fx + 26, fy + 24);
        SelectObject(hdc, fo); DeleteObject(fp);
    }
    /* hint above player */
    UpdateFocus();
    if (g_focusKind) {
        const wchar_t* hint = HINT_TALK;
        if (g_focusKind == 2) hint = HINT_PICK;
        else if (g_focusKind == 3) hint = (g_focusId == 0) ? HINT_PICK : HINT_LEAVE;
        else if (g_focusKind == 1) {
            if (g_focusId == 1) {
                if (g_smithStage == 0) hint = (InvCount(ITEM_METAL) > 0 && g_quest >= 2) ? HINT_HAND : HINT_FORGE;
                else if (g_smithStage == 2) hint = HINT_WAIT;
                else hint = HINT_DONE;
            } else if (g_focusId == 2) {
                if (g_maryaStage == 0) hint = (InvCount(ITEM_CLOTH) > 0 && g_quest >= 2) ? HINT_HAND : HINT_WEAVE;
                else if (g_maryaStage == 2) hint = HINT_WAIT;
                else hint = HINT_DONE;
            }
        }
        TextC(hdc, g_px, g_py - 34, hint, RGB(0xFF,0xE9,0x7A), g_fSmall, 1);
    }
    /* HUD layers */
    PaintPlayerPanel(hdc);
    PaintFocusInfo(hdc);
    PaintAbilityBar(hdc);
    PaintInventory(hdc);
    PaintDialogBox(hdc);
    /* quest tracker under focus info */
    {
        const wchar_t* qtxt;
        switch (g_quest) {
            case 0: qtxt = Q_NONE; break;
            case 1: qtxt = Q_GREET; break;
            case 2: qtxt = Q1; break;
            case 3: qtxt = Q2; break;
            case 4: qtxt = Q3; break;
            case 5: qtxt = Q_PROF; break;
            default: qtxt = Q_FIN; break;
        }
        swprintf(b, 160, L"%ls %ls", Q_TITLE, qtxt);
        TextC(hdc, WIN_W/2, 46, b, RGB(0x9A,0xE0,0x9A), g_fSmall, 1);
    }
    /* bottom hint */
    TextC(hdc, WIN_W/2, WIN_H - 20, W_HINT, RGB(0x7A,0x86,0x9A), g_fSmall, 1);
    (void)r;
}

static void PaintContinue(HWND hwnd, HDC hdc)
{
    wchar_t info[160];
    const wchar_t* cname = (g_selected>=0&&g_selected<NCLASS)? g_class[g_selected].name : L"?";
    (void)hwnd;
    RectFill(hdc, 0, 0, WIN_W, WIN_H, RGB(0x10,0x14,0x20));
    TextC(hdc, WIN_W/2, 120, H_CONT1, RGB(0xE8,0xC8,0x5A), g_fMed, 1);
    swprintf(info, 160, L"%ls \x2014 %ls", g_nick, cname);
    TextC(hdc, WIN_W/2, 160, info, RGB(0xFF,0xFF,0xFF), g_fBig, 1);
    swprintf(info, 160, L"\x0416\x0438\x0437\x043d\x044c: %d/%d \x2022 \x0416\x0435\x043b\x0443\x0434\x0435\x0439: %d", g_hpCur, g_hpMax, g_acorns);
    TextC(hdc, WIN_W/2, 196, info, RGB(0x9A,0xE0,0x9A), g_fSmall, 1);
}

static void OnPaint(HWND hwnd)
{
    PAINTSTRUCT ps;
    HDC hdc = BeginPaint(hwnd, &ps);
    /* double buffer */
    HDC mem = CreateCompatibleDC(hdc);
    HBITMAP bmp = CreateCompatibleBitmap(hdc, WIN_W, WIN_H);
    HBITMAP old = (HBITMAP)SelectObject(mem, bmp);

    switch (g_screen) {
        case SCR_LAUNCH:   PaintLaunch(hwnd, mem);  break;
        case SCR_SELECT:   PaintSelect(hwnd, mem);  break;
        case SCR_LORE:
            RectFill(mem, 0, 0, WIN_W, WIN_H, RGB(0x0C,0x10,0x1A));
            TextC(mem, WIN_W/2, 40, L"\x041f\x0440\x0435\x0434\x0430\x043d\x0438\x0435", RGB(0xE8,0xC8,0x5A), g_fMed, 1);
            TextC(mem, 60, 90, LORE_TEXT, RGB(0xC8,0xC8,0xD8), g_fSmall, 0);
            break;
        case SCR_CONTINUE: PaintContinue(hwnd, mem); break;
        case SCR_WORLD:    PaintWorld(mem);          break;
    }
    BitBlt(hdc, 0, 0, WIN_W, WIN_H, mem, 0, 0, SRCCOPY);
    SelectObject(mem, old);
    DeleteObject(bmp);
    DeleteDC(mem);
    EndPaint(hwnd, &ps);
}

/* --------------------------- Controls per screen -------------------------- */
static HWND mkbtn(HWND parent, const wchar_t* text, int id, int x, int y, int w, int h)
{
    return CreateWindowExW(0, L"BUTTON", text, WS_CHILD | WS_VISIBLE | BS_OWNERDRAW,
                           x, y, w, h, parent, (HMENU)(INT_PTR)id,
                           GetModuleHandle(NULL), NULL);
}
static BOOL CALLBACK DestroyChildCb(HWND c, LPARAM l) { (void)l; DestroyWindow(c); return TRUE; }

static void LayoutForScreen(HWND hwnd)
{
    /* remove all controls, recreate per screen */
    EnumChildWindows(hwnd, DestroyChildCb, 0);
    g_editNick = NULL;

    switch (g_screen) {
        case SCR_LAUNCH:
            mkbtn(hwnd, B_START, IDC_BTN_START, 220, 320, 200, 40);
            mkbtn(hwnd, B_LORE,  IDC_BTN_LORE,  220, 370, 200, 34);
            mkbtn(hwnd, B_EXIT,  IDC_BTN_QUIT,  220, 414, 200, 34);
            break;
        case SCR_SELECT: {
            int i;
            for (i = 0; i < NCLASS; i++) mkbtn(hwnd, L"", IDC_CARD_0 + i, 12 + i * 208, 44, 200, 256);
            g_editNick = CreateWindowExW(0, L"EDIT", L"", WS_CHILD | WS_VISIBLE | WS_BORDER | ES_AUTOHSCROLL,
                                         130, 310, 300, 24, hwnd, (HMENU)(INT_PTR)IDC_EDT_NICK,
                                         GetModuleHandle(NULL), NULL);
            SendMessageW(g_editNick, WM_SETFONT, (WPARAM)g_fMed, TRUE);
            if (g_nick[0]) SetWindowTextW(g_editNick, g_nick);
            mkbtn(hwnd, B_CHOOSE, IDC_BTN_CHOOSE, 220, 348, 200, 36);
            mkbtn(hwnd, B_BACK,   IDC_BTN_BACK,   220, 392, 200, 30);
            break; }
        case SCR_LORE:
            mkbtn(hwnd, B_BACK, IDC_BTN_BACK, 220, 420, 200, 34);
            break;
        case SCR_CONTINUE:
            mkbtn(hwnd, B_CONT, IDC_BTN_CONT, 220, 260, 200, 44);
            mkbtn(hwnd, B_NEW,  IDC_BTN_NEW,  220, 316, 200, 36);
            mkbtn(hwnd, B_BACK, IDC_BTN_BACK, 220, 364, 200, 30);
            break;
        case SCR_WORLD:
            break;
    }
    InvalidateRect(hwnd, NULL, TRUE);
}

/* ----------------------------- Interaction -------------------------------- */
static void EnterWorld(HWND hwnd)
{
    BuildAbilities(); /* class-dependent hotbar */
    g_screen = SCR_WORLD;
    SetTimer(hwnd, 2, 50, NULL);   /* mouse-walk / regen tick */
    LayoutForScreen(hwnd);
    SetFocus(hwnd);
    SaveProfile(); /* real-time: entering the world is persisted instantly */
}

static void TryPickAcorn(HWND hwnd)
{
    int i, best = -1; double bd = 1e9;
    for (i = 0; i < 3; i++) {
        int dx, dy; double d;
        if (g_acorns_arr[i].taken) continue;
        dx = g_px - g_acorns_arr[i].x; dy = g_py - g_acorns_arr[i].y;
        d = sqrt((double)(dx*dx + dy*dy));
        if (d < PICK_R && d < bd) { bd = d; best = i; }
    }
    if (best < 0) return;
    g_acorns_arr[best].taken = 1;
    g_acorns++;
    InvAdd(ITEM_ACORN, 1);
    if (g_quest == 2 && g_acorns >= 3) { g_quest = 3; QuestAdvanceCheck(); }
    SaveProfile();               /* real-time autosave on loot */
    InvalidateRect(hwnd, NULL, FALSE);
}

static void TalkCat(HWND hwnd)
{
    if (g_dialogShown) { g_dialogShown = 0; InvalidateRect(hwnd, NULL, FALSE); return; }
    /* step machine:
       0 not greeted -> greet, start task1
       1 greeted     -> give acorn task + starter items (metal/cloth/potion)
       2 acorns pending
       3 smith pending
       4 marya pending
       5 all done -> profession choice screen
       6 hero (profession chosen) */
    switch (g_quest) {
        case 0: {
            wchar_t greet[320];
            swprintf(greet, 320, D_CAT_NEW, g_nick[0] ? g_nick : L"???");
            ShowDialogTop(greet);
            g_catTalked = 1;
            g_quest = 1;
            SaveProfile();
            return; }
        case 1:
            ShowDialogTop(D_CAT_Q1);
            /* starter kit: metal for smith, cloth for marya, potion */
            InvAdd(ITEM_METAL, 1); InvAdd(ITEM_CLOTH, 1); InvAdd(ITEM_POTION, 2);
            g_quest = 2;
            SaveProfile();
            return;
        case 2:
            if (g_acorns >= 3) {
                InvAdd(ITEM_ACORN, 0);
                ShowDialogTop(D_CAT_Q2);
                g_quest = 3;
            } else {
                wchar_t b[128];
                swprintf(b, 128, D_CAT_PROGRESS, g_acorns);
                ShowDialogTop(b);
            }
            SaveProfile();
            return;
        case 3:
            ShowDialogTop(g_smithStage >= 3 ? D_CAT_Q3 : D_CAT_NEED2);
            if (g_smithStage >= 3) g_quest = 4;
            SaveProfile();
            return;
        case 4:
            ShowDialogTop(g_maryaStage >= 3 ? D_CAT_FINAL : D_CAT_NEED3);
            if (g_maryaStage >= 3) g_quest = 5;
            SaveProfile();
            return;
        case 5:
            ShowDialogTop(D_CAT_FINAL);
            g_screen = SCR_PROF;           /* open profession choice overlay */
            LayoutForScreen(hwnd);
            return;
        default:
            ShowDialogTop(D_CAT_AGAIN);
            return;
    }
}

static void QuestAdvanceCheck(void)
{
    /* called when any task completes; if all 3 done -> go back to the cat */
    if (g_quest == 5) return;
}

/* ---- NPC interactions ---------------------------------------------------- */
static void TalkSmith(HWND hwnd)
{
    ULONGLONG now = GetTickCount64();
    if (g_dialogShown) { g_dialogShown = 0; InvalidateRect(hwnd, NULL, FALSE); return; }
    if (g_smithStage == 0) {
        if (InvCount(ITEM_METAL) > 0 && g_quest >= 2) {
            InvRemove(ITEM_METAL, 1);
            g_smithStage = 2;                    /* crafting */
            g_smithDoneAt = now + 4000;          /* 4 seconds of forge work */
            ShowDialogTop(D_SMITH_GIVE);
            if (g_quest == 2) g_quest = 3;       /* acorns already done? keep as is */
            SaveProfile();
        } else {
            ShowDialogTop(D_HAND_EMPTY);
        }
        return;
    }
    if (g_smithStage == 2) {
        if (now >= g_smithDoneAt) {
            g_smithStage = 3;
            InvAdd(ITEM_BULAVA, 1); InvAdd(ITEM_LUKO, 1); InvAdd(ITEM_POSOH, 1);
            InvAdd(ITEM_AMULET, 1);
            ShowDialogTop(D_SMITH_GOLD);
            if (g_quest == 3 && g_maryaStage >= 3) g_quest = 5;
            SaveProfile();
        } else {
            ShowDialogTop(D_SMITH_WAIT);
        }
        return;
    }
    ShowDialogTop(D_SMITH_GOLD);   /* already armed: hint */
    (void)hwnd;
}

static void TalkMarya(HWND hwnd)
{
    ULONGLONG now = GetTickCount64();
    if (g_dialogShown) { g_dialogShown = 0; InvalidateRect(hwnd, NULL, FALSE); return; }
    if (g_maryaStage == 0) {
        if (InvCount(ITEM_CLOTH) > 0 && g_quest >= 2) {
            InvRemove(ITEM_CLOTH, 1);
            g_maryaStage = 2;
            g_maryaDoneAt = now + 4000;
            ShowDialogTop(D_MARYA_GIVE);
            SaveProfile();
        } else {
            ShowDialogTop(D_HAND_EMPTY);
        }
        return;
    }
    if (g_maryaStage == 2) {
        if (now >= g_maryaDoneAt) {
            g_maryaStage = 3;
            InvAdd(ITEM_HEAVY, 1); InvAdd(ITEM_LEATHER, 1); InvAdd(ITEM_MANTLE, 1);
            ShowDialogTop(D_MARYA_GOLD);
            if (g_quest == 3 && g_smithStage >= 3) g_quest = 5;
            SaveProfile();
        } else {
            ShowDialogTop(D_MARYA_WAIT);
        }
        return;
    }
    ShowDialogTop(D_MARYA_GOLD);
    (void)hwnd;
}

/* profession choice (after all 3 tasks): 0 Воин, 1 Лучник, 2 Волхв */
static void ChooseProfession(HWND hwnd, int idx)
{
    const wchar_t* pnames[3];
    wchar_t b[256];
    g_selected = idx;                    /* hotbar follows the profession */
    g_profBonus = 5;
    g_youngster = 0;
    g_level++;
    g_hpMax += 20; g_hpCur = g_hpMax;    /* level-up heal */
    g_energyMax += 5; g_energyCur = g_energyMax;
    g_quest = 6;
    pnames[0] = PR_WARRIOR; pnames[1] = PR_HUNTER; pnames[2] = PR_MAGUS;
    swprintf(b, 256, D_PROF_DONE, pnames[idx]);
    BuildAbilities();
    SaveProfile();
    g_screen = SCR_WORLD;
    LayoutForScreen(hwnd);
    ShowDialogTop(b);
    InvalidateRect(hwnd, NULL, FALSE);
}

static void SetFocusNpc(int kind, int id, const wchar_t* name)
{
    g_focusKind = kind; g_focusId = id;
    lstrcpynW(g_focusName, name, 64);
}
static void UpdateFocus(void)
{
    double d, bd = 1e9; int kind = 0, id = 0; const wchar_t* nm = L"";
    /* cat */
    d = sqrt((double)((g_px-CAT_X)*(g_px-CAT_X) + (g_py-CAT_Y)*(g_py-CAT_Y)));
    if (d < TALK_R && d < bd) { bd = d; kind = 1; id = 0; nm = CAT_NAME; }
    /* smith */
    d = sqrt((double)((g_px-SMITH_X)*(g_px-SMITH_X) + (g_py-SMITH_Y)*(g_py-SMITH_Y)));
    if (d < TALK_R && d < bd) { bd = d; kind = 1; id = 1; nm = NPC_SMITH; }
    /* marya */
    d = sqrt((double)((g_px-MARYA_X)*(g_px-MARYA_X) + (g_py-MARYA_Y)*(g_py-MARYA_Y)));
    if (d < TALK_R && d < bd) { bd = d; kind = 1; id = 2; nm = NPC_MARYA; }
    /* oak */
    d = sqrt((double)((g_px-OAK_X)*(g_px-OAK_X) + (g_py-(OAK_Y+20))*(g_py-(OAK_Y+20))));
    if (d < PICK_R + 24 && d < bd) { bd = d; kind = 3; id = 0; nm = T_OAK; }
    /* acorns */
    {
        int i;
        for (i = 0; i < 3; i++) {
            if (g_acorns_arr[i].taken) continue;
            d = sqrt((double)((g_px-g_acorns_arr[i].x)*(g_px-g_acorns_arr[i].x) +
                              (g_py-g_acorns_arr[i].y)*(g_py-g_acorns_arr[i].y)));
            if (d < PICK_R && d < bd) { bd = d; kind = 2; id = ITEM_ACORN; nm = T_ACORN; }
        }
    }
    /* dark grove spot */
    d = sqrt((double)((g_px-SPOT_X)*(g_px-SPOT_X) + (g_py-SPOT_Y)*(g_py-SPOT_Y)));
    if (d < 46 && d < bd) { bd = d; kind = 3; id = 1; nm = T_SPOT; }
    if (!kind) { g_focusKind = 0; g_focusId = 0; g_focusName[0] = 0; }
    else       { SetFocusNpc(kind, id, nm); }
}

/* Collision test for a single point (shared by keyboard and mouse movement) */
static int BlockedAt(int nx, int ny)
{
    if (nx < 14 || nx > WIN_W - 14) return 1;
    if (ny < 96  || ny > WIN_H - 40) return 1;
    if (abs(nx - OAK_X) < 16 && ny > OAK_Y && ny < OAK_Y + 50) return 1; /* trunk */
    if (nx > 40 && nx < 136 && ny > 120 && ny < 200) return 1;            /* hut1 */
    if (nx > 500 && nx < 600 && ny > 118 && ny < 200) return 1;           /* hut2 */
    if (nx > 150 && nx < 190 && ny > 250 && ny < 276) return 1;           /* well */
    return 0;
}

static void MovePlayer(HWND hwnd, int dx, int dy)
{
    int nx = g_px + dx, ny = g_py + dy;
    if (!BlockedAt(nx, ny)) { g_px = nx; g_py = ny; }
    g_walkDestSet = 0; /* manual keys cancel the mouse walk order */
    /* real-time throttled autosave (every 2s while moving) */
    if (GetTickCount64() - g_lastSave > 2000) SaveProfile();
    InvalidateRect(hwnd, NULL, FALSE);
}

/* Mouse-driven walking: LMB sets destination, hero walks there each tick */
static void WalkToward(HWND hwnd)
{
    double dx, dy, d;
    if (!g_walkDestSet) return;
    dx = g_walkX - g_px; dy = g_walkY - g_py;
    d = sqrt(dx * dx + dy * dy);
    if (d < WALK_SPEED) { g_px = g_walkX; g_py = g_walkY; g_walkDestSet = 0; }
    else {
        int nx = g_px + (int)(dx / d * WALK_SPEED);
        int ny = g_py + (int)(dy / d * WALK_SPEED);
        if (BlockedAt(nx, ny)) { g_walkDestSet = 0; } /* obstacle: stop */
        else { g_px = nx; g_py = ny; }
    }
    if (GetTickCount64() - g_lastSave > 2000) SaveProfile();
    InvalidateRect(hwnd, NULL, FALSE);
}

/* ------------------------------- Abilities -------------------------------- */
static void CastAbility(HWND hwnd, int slot)
{
    ULONGLONG now = GetTickCount64();
    Ability* ab;
    int r, dmg, i;
    if (slot < 0 || slot >= NABILITY || g_selected < 0) return;
    ab = &g_ab[slot];
    if (ab->cd > 1000 && now < ab->cdUntil) return;      /* on cooldown */
    if (g_energyCur < ab->cost) {                        /* not enough energy */
        ShowDialogTop(D_ENERGY);
        return;
    }
    g_energyCur -= ab->cost;
    ab->lastCast = now;
    if (ab->cd > 1000) { ab->cdUntil = now + ab->cd; ab->readyAt = ab->cdUntil; }
    else               { ab->readyAt = now + ab->cd; }

    switch (ab->kind) {
        case AB_HEAL:
            r = ab->power;
            if (g_hpCur < g_hpMax) g_hpCur += r; if (g_hpCur > g_hpMax) g_hpCur = g_hpMax;
            if (g_energyCur < g_energyMax) g_energyCur += 10; if (g_energyCur > g_energyMax) g_energyCur = g_energyMax;
            break;
        case AB_BUFF:
            g_buffUntil = now + 8000; /* +50% damage for 8 s */
            break;
        case AB_PICK:
            for (i = 0; i < 3; i++) {
                int ddx = g_px - g_acorns_arr[i].x, ddy = g_py - g_acorns_arr[i].y;
                if (!g_acorns_arr[i].taken && sqrt((double)(ddx*ddx+ddy*ddy)) < PICK_R + 36) {
                    g_acorns_arr[i].taken = 1; g_acorns++;
                    InvAdd(ITEM_ACORN, 1);
                    if (g_quest == 2 && g_acorns >= 3) { g_quest = 3; QuestAdvanceCheck(); }
                    break;
                }
            }
            break;
        case AB_DMG: default:
            dmg = ab->power;
            if (now < g_buffUntil) dmg = dmg * 3 / 2;
            r = g_hpCur - dmg; if (r < 0) r = 0; g_hpCur = r;
            break;
    }
    SaveProfile(); /* real-time: ability use is persisted instantly */
    InvalidateRect(hwnd, NULL, FALSE);
}

static void DrawAbilityBar(HDC hdc)
{
    static const wchar_t* AB_KEY[4] = { L"1", L"2", L"3", L"4" };
    ULONGLONG now = GetTickCount64();
    int bx = 250, by = 444, bw = 88, gap = 6, i;
    for (i = 0; i < NABILITY; i++) {
        Ability* ab = &g_ab[i];
        RECT r = { bx + i * (bw + gap), by, bx + i * (bw + gap) + bw, by + 30 };
        ULONGLONG left = 0;
        HBRUSH b;
        int ready = !(ab->cd > 1000 && now < ab->cdUntil) && g_energyCur >= ab->cost;
        b = CreateSolidBrush(ready ? RGB(0x2A,0x30,0x44) : RGB(0x18,0x1A,0x24));
        FillRect(hdc, &r, b); DeleteObject(b);
        DrawFrame(hdc, r, ready ? RGB(0xC8,0x9A,0x3E) : RGB(0x55,0x50,0x44));
        /* cooldown sweep overlay */
        if (ab->cd > 1000 && now < ab->cdUntil) {
            RECT cr = r;
            left = ab->cdUntil - now;
            cr.left = r.left + (LONG)((double)(r.right - r.left) * (1.0 - (double)left / ab->cd));
            b = CreateSolidBrush(RGB(0x10,0x12,0x1A));
            FillRect(hdc, &cr, b); DeleteObject(b);
        }
        TextC(hdc, r.left + 4,  r.top + 2, ab->name,   RGB(0xFF,0xF3,0xC0), g_fSmall, 0);
        TextC(hdc, r.left + 4,  r.top + 16, ab->tag,   ready ? RGB(0x9A,0xAA,0xFF) : RGB(0x77,0x77,0x88), g_fSmall, 0);
        TextC(hdc, r.right - 12, r.top + 2, AB_KEY[i], RGB(0xE8,0xC8,0x5A), g_fSmall, 0);
        if (ab->cd > 1000 && left) {
            wchar_t s[8]; swprintf(s, 8, L"%d", (int)((left + 999) / 1000));
            TextC(hdc, (r.left + r.right)/2, r.top + 8, s, RGB(0xFF,0xFF,0xFF), g_fMed, 1);
        }
    }
}

static void AdvanceTick(HWND hwnd)
{
    int changed = 0;
    ULONGLONG now = GetTickCount64();
    if (g_screen == SCR_WORLD) {
        WalkToward(hwnd);
        /* passive energy regen: +1 every 2 s up to max */
        if (g_energyCur < g_energyMax && now - g_lastRegen >= 2000) {
            g_energyCur++; g_lastRegen = now; changed = 1;
        }
        if (g_buffUntil && now > g_buffUntil) { g_buffUntil = 0; changed = 1; }
        if (g_dialogShown && now > g_dialogUntil) { g_dialogShown = 0; changed = 1; }
        if (changed) InvalidateRect(hwnd, NULL, FALSE);
    }
}

/* ------------------------------ Window proc ------------------------------- */
static LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    static int hasProfile = -1;

    switch (msg) {
        case WM_CREATE: {
            int i;
            HINSTANCE hi = ((LPCREATESTRUCT)lp)->hInstance;
            g_fTitle = CreateFontW(64, 0, 0, 0, FW_BOLD, 0, 0, 0, DEFAULT_CHARSET,
                                  OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, ANTIALIASED_QUALITY, FF_DONTCARE, L"Segoe UI");
            g_fBig   = CreateFontW(28, 0, 0, 0, FW_BOLD, 0, 0, 0, DEFAULT_CHARSET,
                                  OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, ANTIALIASED_QUALITY, FF_DONTCARE, L"Segoe UI");
            g_fMed   = CreateFontW(18, 0, 0, 0, FW_NORMAL, 0, 0, 0, DEFAULT_CHARSET,
                                  OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, ANTIALIASED_QUALITY, FF_DONTCARE, L"Segoe UI");
            g_fSmall = CreateFontW(14, 0, 0, 0, FW_NORMAL, 0, 0, 0, DEFAULT_CHARSET,
                                  OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, ANTIALIASED_QUALITY, FF_DONTCARE, L"Segoe UI");
            for (i = 0; i < 4; i++) { HFONT f = i==0?g_fTitle:i==1?g_fBig:i==2?g_fMed:g_fSmall; (void)f; }
            (void)hi;
            hasProfile = LoadProfile();
            SetTimer(hwnd, 1, 250, NULL); /* dialog auto-hide tick */ SetTimer(hwnd, 2, 50, NULL); /* walk/regen tick (no-op outside world) */
            LayoutForScreen(hwnd);
            return 0;
        }
        case WM_TIMER:
            AdvanceTick(hwnd);
            return 0;
        case WM_CTLCOLORSTATIC:
        case WM_CTLCOLOREDIT:
            SetBkColor((HDC)wp, RGB(0x1A,0x1E,0x2C));
            SetTextColor((HDC)wp, RGB(0xFF,0xFF,0xFF));
            return (LRESULT)GetStockObject(BLACK_BRUSH);
        case WM_DRAWITEM: {
            LPDRAWITEMSTRUCT di = (LPDRAWITEMSTRUCT)lp;
            const wchar_t* txt = NULL;
            COLORREF bg = RGB(0x2A,0x30,0x44), fg = RGB(0xFF,0xFF,0xFF), br = RGB(0xC8,0x9A,0x3E);
            wchar_t buf[64];
            switch (di->CtlID) {
                case IDC_BTN_START: txt = B_START; bg = RGB(0x3A,0x4A,0x8B); break;
                case IDC_BTN_LORE:  txt = B_LORE;  break;
                case IDC_BTN_QUIT:  txt = B_EXIT;  bg = RGB(0x5A,0x2A,0x2A); break;
                case IDC_BTN_BACK:  txt = B_BACK;  break;
                case IDC_BTN_CHOOSE:txt = B_CHOOSE;bg = RGB(0x3A,0x6B,0x3F); break;
                case IDC_BTN_CONT:  txt = B_CONT;  bg = RGB(0x3A,0x6B,0x3F); break;
                case IDC_BTN_NEW:   txt = B_NEW;   break;
                case IDC_CARD_0: case IDC_CARD_1: case IDC_CARD_2: {
                    int idx = di->CtlID - IDC_CARD_0;
                    RECT r = di->rcItem;
                    HBRUSH b = CreateSolidBrush(di->itemState & ODS_SELECTED ? RGB(0x2A,0x34,0x50) : RGB(0x1A,0x1E,0x2C));
                    FillRect(di->hDC, &r, b); DeleteObject(b);
                    if (g_selected == idx) {
                        HPEN p = CreatePen(PS_SOLID, 3, RGB(0xFF,0xE9,0x7A));
                        HPEN o = (HPEN)SelectObject(di->hDC, p);
                        SelectObject(di->hDC, GetStockObject(NULL_BRUSH));
                        Rectangle(di->hDC, r.left, r.top, r.right, r.bottom);
                        SelectObject(di->hDC, o); DeleteObject(p);
                    }
                    return TRUE; }
                default: {
                    if (GetDlgItemTextW(hwnd, (int)di->CtlID, buf, 64)) txt = buf; else txt = L"";
                }
            }
            {
                RECT r = di->rcItem;
                HBRUSH b = CreateSolidBrush(bg);
                FillRect(di->hDC, &r, b); DeleteObject(b);
                DrawFrameAt(di->hDC, r, br);
                SetBkMode(di->hDC, TRANSPARENT);
                SetTextColor(di->hDC, fg);
                SelectObject(di->hDC, g_fMed);
                DrawTextW(di->hDC, txt, -1, &r, DT_CENTER | DT_VCENTER | DT_SINGLELINE);
            }
            return TRUE;
        }
        case WM_PAINT:
            OnPaint(hwnd);
            return 0;
        case WM_KEYDOWN:
            if (g_screen != SCR_WORLD) return 0;
            switch (wp) {
                case '1': CastAbility(hwnd, 0); break;
                case '2': CastAbility(hwnd, 1); break;
                case '3': CastAbility(hwnd, 2); break;
                case '4': CastAbility(hwnd, 3); break;
                case VK_LEFT:  case 'A': MovePlayer(hwnd, -8, 0); break;
                case VK_RIGHT: case 'D': MovePlayer(hwnd,  8, 0); break;
                case VK_UP:    case 'W': MovePlayer(hwnd, 0, -8); break;
                case VK_DOWN:  case 'S': MovePlayer(hwnd, 0,  8); break;
                case 'E': {
                    int dx = g_px - CAT_X, dy = g_py - CAT_Y;
                    if (sqrt((double)(dx*dx+dy*dy)) < TALK_R) TalkCat(hwnd);
                    else TryPickAcorn(hwnd);
                    break; }
                case VK_ESCAPE:
                    KillTimer(hwnd, 2);
                    g_walkDestSet = 0;
                    g_screen = SCR_CONTINUE; /* back to menu keeps profile */
                    LayoutForScreen(hwnd);
                    break;
            }
            return 0;
        case WM_LBUTTONDOWN:
            if (g_screen == SCR_WORLD) {
                if (g_dialogShown) { g_dialogShown = 0; InvalidateRect(hwnd, NULL, FALSE); }
                else {
                    /* mouse-to-walk: hero walks to the clicked point */
                    int mx = GET_X_LPARAM(lp), my = GET_Y_LPARAM(lp);
                    if (mx >= 14 && mx <= WIN_W - 14 && my >= 96 && my <= WIN_H - 40 &&
                        !BlockedAt(mx, my)) {
                        g_walkX = mx; g_walkY = my; g_walkDestSet = 1;
                        InvalidateRect(hwnd, NULL, FALSE);
                    }
                }
            }
            return 0;
        case WM_COMMAND:
            switch (LOWORD(wp)) {
                case IDC_BTN_START:
                    if (hasProfile == 1) { g_screen = SCR_CONTINUE; }
                    else                 { g_screen = SCR_SELECT; }
                    LayoutForScreen(hwnd);
                    break;
                case IDC_BTN_LORE:
                    g_screen = SCR_LORE; LayoutForScreen(hwnd); break;
                case IDC_BTN_QUIT:
                    DestroyWindow(hwnd); break;
                case IDC_BTN_BACK:
                    g_screen = (hasProfile == 1) ? SCR_CONTINUE : SCR_LAUNCH;
                    LayoutForScreen(hwnd);
                    break;
                case IDC_CARD_0: case IDC_CARD_1: case IDC_CARD_2: {
                    int idx = LOWORD(wp) - IDC_CARD_0;
                    g_selected = idx;
                    g_hpMax = g_class[idx].hp; g_hpCur = g_class[idx].hp;
                    g_energyMax = g_class[idx].energy; g_energyCur = g_class[idx].energy;
                    BuildAbilities(); /* hotbar preview follows the class */
                    LayoutForScreen(hwnd); /* repaint selection */
                    break; }
                case IDC_BTN_CHOOSE: {
                    wchar_t nick[64];
                    if (g_selected < 0) { MessageBoxW(hwnd, B_NEED, APP_TITLE, MB_OK | MB_ICONWARNING); break; }
                    GetWindowTextW(g_editNick, nick, 63);
                    if (!nick[0]) { MessageBoxW(hwnd, H_WARN, APP_TITLE, MB_OK | MB_ICONWARNING); break; }
                    lstrcpynW(g_nick, nick, 64);
                    g_questStep = 0; g_acorns = 0; g_catTalked = 0;
                    g_px = 320; g_py = 380;
                    memset(g_acorns_arr, 0, sizeof(g_acorns_arr));
                    hasProfile = 1;
                    SaveProfile(); /* real-time: character creation persists now */
                    EnterWorld(hwnd);
                    break; }
                case IDC_BTN_CONT:
                    EnterWorld(hwnd);
                    break;
                case IDC_BTN_NEW:
                    hasProfile = 0;
                    g_selected = -1; g_nick[0] = 0;
                    g_screen = SCR_SELECT;
                    LayoutForScreen(hwnd);
                    break;
            }
            return 0;
        case WM_CLOSE:
            SaveProfile(); /* persist on exit */
            DestroyWindow(hwnd);
            return 0;
        case WM_DESTROY:
            KillTimer(hwnd, 1);
            PostQuitMessage(0);
            return 0;
    }
    return DefWindowProcW(hwnd, msg, wp, lp);
}

/* helper: frame at rect with color (DrawFrame expects RECT value) */
static void DrawFrameAt(HDC hdc, RECT r, COLORREF c)
{
    HPEN pen = CreatePen(PS_SOLID, 2, c);
    HPEN old = (HPEN)SelectObject(hdc, pen);
    SelectObject(hdc, GetStockObject(NULL_BRUSH));
    Rectangle(hdc, r.left, r.top, r.right, r.bottom);
    SelectObject(hdc, old);
    DeleteObject(pen);
}

int WINAPI WinMain(HINSTANCE hi, HINSTANCE ph, LPSTR cl, int cs)
{
    WNDCLASSW wc = {0};
    HWND hwnd;
    MSG m;
    RECT rc = {0, 0, WIN_W, WIN_H};
    DWORD style = WS_OVERLAPPEDWINDOW & ~(WS_THICKFRAME | WS_MAXIMIZEBOX);
    int sw = GetSystemMetrics(SM_CXSCREEN), sh = GetSystemMetrics(SM_CYSCREEN);
    int x, y;

    AdjustWindowRect(&rc, style, FALSE);
    x = (sw - (rc.right - rc.left)) / 2;
    y = (sh - (rc.bottom - rc.top)) / 2;

    wc.lpfnWndProc = WndProc;
    wc.hInstance = hi;
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    wc.hbrBackground = (HBRUSH)GetStockObject(BLACK_BRUSH);
    wc.lpszClassName = L"YavProtoWnd";
    RegisterClassW(&wc);

    hwnd = CreateWindowExW(0, wc.lpszClassName, APP_TITLE, style,
                           x, y, rc.right - rc.left, rc.bottom - rc.top,
                           NULL, NULL, hi, NULL);
    ShowWindow(hwnd, SW_SHOW);
    UpdateWindow(hwnd);

    while (GetMessageW(&m, NULL, 0, 0)) {
        TranslateMessage(&m);
        DispatchMessageW(&m);
    }
    (void)ph; (void)cl; (void)cs;
    return (int)m.wParam;
}
