/* ==========================================================================
 * "YAV: Zabytye Byliny" (YAV: Forgotten Epic Tales) - Windows test build v0.3
 * --------------------------------------------------------------------------
 * Fixed window 640x480. Flow:
 *   Launch screen -> Character select (Bogatyr/Strelek/Volkhv) -> World
 * If a profile file exists next to the exe, player gets "CONTINUE / NEW".
 * Real-time autosave: every action (choice, nickname, movement, quest step)
 * is written to yav_profile.json immediately (atomic write via temp+rename).
 *
 * v0.2: small village scene with an oak tree in the center and the
 * NPC "Cat the Scholar" (Kot Ucheny) who greets the hero and gives the
 * first quest ("Greet the scholar cat" -> "Collect 3 acorns near the oak").
 *
 * v0.3 controls:
 *   - Mouse-to-walk: left-click anywhere on the ground and the hero walks
 *     there automatically (collision-aware: huts, well, oak trunk, bounds).
 *     Arrow keys / WASD still work as manual override.
 *   - Ability hotbar (keys 1..4): class-specific skills with energy cost,
 *     cooldown sweep animation and countdown; passive energy regen (+1/2s);
 *     HP + energy bars in HUD; ESC returns to menu.
 * Architecture note (mirrors Unity project): logic (stats, quest state,
 * persistence) is separated from rendering; later this exact state model
 * moves behind a server-authoritative network layer.
 * Generated by Prototype/gen.py - edit gen.py, not this file.
 * ========================================================================== */
#define WINVER 0x0A00
#define _WIN32_WINNT 0x0A00
#include <windows.h>
#include <windowsx.h>   /* GET_X_LPARAM / GET_Y_LPARAM for mouse-to-walk */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <stdarg.h>
#include <math.h>

#define NCLASS 3
#define WIN_W 640
#define WIN_H 480

#define IDC_BTN_START  101
#define IDC_BTN_LORE   102
#define IDC_BTN_QUIT   103
#define IDC_CARD_0     201
#define IDC_CARD_1     202
#define IDC_CARD_2     203
#define IDC_BTN_BACK   204
#define IDC_BTN_CHOOSE 205
#define IDC_EDT_NICK   206
#define IDC_BTN_OK     207
#define IDC_BTN_CONT   111
#define IDC_BTN_NEW    112

enum { SCR_LAUNCH, SCR_SELECT, SCR_LORE, SCR_CONTINUE, SCR_WORLD };

typedef struct {
    const wchar_t* name;
    const wchar_t* tag;
    const wchar_t* desc;
    COLORREF color;
    int hp, dmg, energy, carry;
} ClassDef;

static ClassDef g_class[NCLASS] = {
    { L"\x0411\x043e\x0433\x0430\x0442\x044b\x0440\x044c", L"\x0422\x0430\x043d\x043a / \x0431\x043b\x0438\x0436\x043d\x0438\x0439 \x0431\x043e\x0439", L"\x041a\x0440\x0435\x0441\x0442\x044c\x044f\x043d\x0441\x043a\x0438\x0439 \x0441\x044b\x043d, \x043f\x043e\x0434\x043d\x044f\x0432\x0448\x0438\x0439 \x0434\x0443\x0431\x043e\x0432\x0443\x044e \x043f\x0430\x043b\x0438\x0446\x0443. \x041a\x0440\x0435\x043f\x043a\x0438\x0439 \x0442\x0435\x043b\x043e\x043c, \x0438\x0434\x0451\x0442 \x0432\x043f\x0435\x0440\x0451\x0434 \x2014 \x0440\x0443\x0431\x0438\x0442 \x043d\x0435\x0436\x0438\x0442\x044c \x0432 \x0431\x043b\x0438\x0436\x043d\x0435\x043c \x0431\x043e\x0435 \x0438 \x043d\x043e\x0441\x0438\x0442 \x0431\x043e\x043b\x044c\x0448\x0435 \x0432\x0441\x0435\x0445 \x043b\x0443\x0442\x0430.", RGB(0x2F,0x3A,0x8B), 150, 18, 60, 50 },
    { L"\x0421\x0442\x0440\x0435\x043b\x043e\x043a", L"\x0414\x0430\x043b\x044c\x043d\x0438\x0439 \x0444\x0438\x0437\x0438\x0447\x0435\x0441\x043a\x0438\x0439 \x0443\x0440\x043e\x043d", L"\x041e\x0445\x043e\x0442\x043d\x0438\x043a-\x0441\x043b\x0435\x0434\x043e\x043f\x044b\x0442 \x0438\x0437 \x0433\x043b\x0443\x0431\x0438\x0445 \x043b\x0435\x0441\x043e\x0432. \x0411\x044c\x0451\x0442 \x0438\x0437\x0434\x0430\x043b\x0435\x043a\x0430 \x0442\x043e\x0447\x043d\x043e\x0439 \x0441\x0442\x0440\x0435\x043b\x043e\x0439, \x0431\x044b\x0441\x0442\x0440\x043e \x0445\x043e\x0434\x0438\x0442 \x0438 \x0431\x044b\x0441\x0442\x0440\x043e \x0433\x0438\x0431\x043d\x0435\x0442 \x0432\x0431\x043b\x0438\x0437\x0438.", RGB(0x3A,0x6B,0x3F), 100, 24, 80, 20 },
    { L"\x0412\x043e\x043b\x0445\x0432", L"\x041c\x0430\x0433\x0438\x044f / \x043f\x043e\x0434\x0434\x0435\x0440\x0436\x043a\x0430", L"\x041d\x043e\x0441\x0438\x0442\x0435\x043b\x044c \x0434\x0440\x0435\x0432\x043d\x0438\x0445 \x0437\x0430\x0433\x043e\x0432\x043e\x0440\x043e\x0432. \x0422\x0432\x043e\x0440\x0438\x0442 \x043e\x0433\x043e\x043d\x044c \x0438 \x043c\x043e\x0440\x043e\x043a\x0438, \x043d\x043e \x0442\x0435\x043b\x043e\x043c \x043d\x0435\x043c\x043e\x0449\x0435\x043d. \x0412 \x0433\x0440\x0443\x043f\x043f\x0435 \x2014 \x043f\x043e\x0434\x0434\x0435\x0440\x0436\x043a\x0430 \x0438 \x043a\x043e\x043d\x0442\x0440\x043e\x043b\x044c \x0442\x043e\x043b\x043f\x044b.", RGB(0x7A,0x4A,0x4A), 80, 30, 160, 0 },
};

static const wchar_t* APP_TITLE = L"\x042f\x0412\x042c: \x0417\x0430\x0431\x044b\x0442\x044b\x0435 \x0411\x044b\x043b\x0438\x043d\x044b";
static const wchar_t* S_LOGO    = L"\x042f \x0412 \x042c";
static const wchar_t* S_SLOGAN  = L"\x0417\x0430\x0431\x044b\x0442\x044b\x0435 \x0411\x044b\x043b\x0438\x043d\x044b \x0437\x043e\x0432\x0443\x0442";
static const wchar_t* S_SUBT    = L"\x041f\x0440\x043e\x0442\x043e\x0442\x0438\x043f v0.2 \x2014 \x0437\x0430\x043f\x0443\x0441\x043a, \x0432\x044b\x0431\x043e\x0440 \x0433\x0435\x0440\x043e\x044f, \x0434\x0435\x0440\x0435\x0432\x043d\x044f";
static const wchar_t* B_START   = L"\x041d\x0410\x0427\x0410\x0422\x042c \x0418\x0413\x0420\x0423";
static const wchar_t* B_LORE    = L"\x041f\x0420\x0415\x0414\x0410\x041d\x0418\x0415";
static const wchar_t* B_EXIT    = L"\x0412\x042b\x0425\x041e\x0414";
static const wchar_t* B_BACK    = L"\x041d\x0430\x0437\x0430\x0434";
static const wchar_t* B_CHOOSE  = L"\x0412\x042b\x0411\x0420\x0410\x0422\x042c \x0413\x0415\x0420\x041e\x042f";
static const wchar_t* B_NEED    = L"\x0421\x043d\x0430\x0447\x0430\x043b\x0430 \x0432\x044b\x0431\x0435\x0440\x0438 \x0433\x0435\x0440\x043e\x044f";
static const wchar_t* H_WARN    = L"\x0412\x0432\x0435\x0434\x0438 \x0438\x043c\x044f \x0433\x0435\x0440\x043e\x044f!";
static const wchar_t* B_OK      = L"\x041f\x041e\x041d\x042f\x0422\x041d\x041e";
static const wchar_t* LORE_TEXT = L"\x0414\x0430\x0432\x043d\x043e \x044d\x0442\x043e \x0431\x044b\x043b\x043e, \x0438\x043b\x044c \x0442\x043e\x043b\x044c\x043a\x043e \x0441\x043d\x0438\x0442\x0441\x044f?\n\x041a\x043e\x043b\x043e\x0434\x0435\x0446 \x0432\x0440\x0435\x043c\x0451\x043d \x043c\x0443\x0442\x0438\x043b \x0432\x043e\x0434\x0443, \x0438 \x0441\x0442\x0451\x043b\x0441\x044c\n\x043c\x0435\x0436\x0434\x0443 \x042f\x0432\x044c\x0435\x0439 \x0438 \x041d\x0430\x0432\x044c\x044e \x0442\x043e\x043d\x043a\x0430\x044f \x0433\x0440\x0430\x043d\x044c.\n\n\x0417\x0430\x0431\x044b\x0442\x044b \x0438\x043c\x0435\x043d\x0430 \x0431\x043e\x0433\x0430\x0442\x044b\x0440\x0435\x0439, \x043f\x043e\x0442\x0443\x0445\x043b\x0438\n\x043a\x043e\x0441\x0442\x0440\x044b \x0432 \x043f\x0443\x0441\x0442\x044b\x0445 \x0434\x0435\x0440\x0435\x0432\x043d\x044f\x0445, \x0430 \x0431\x044b\x043b\x0438\x043d\x044b\n\x0441\x043f\x044f\x0442 \x043d\x0430 \x0434\x043d\x0435 \x0447\x0451\x0440\x043d\x044b\x0445 \x043e\x0437\x0451\x0440.\n\n\x041d\x043e \x041d\x0430\x0432\x044c \x043d\x0435 \x0441\x043f\x0438\x0442. \x041e\x043d\x0430 \x043f\x043e\x0434\x0441\x044b\x043b\x0430\x0435\x0442 \x043d\x0435\x0436\x0438\x0442\x044c,\n\x043c\x043e\x0440\x043e\x0447\x0438\x0442 \x043b\x0435\x0441, \x043c\x0430\x043d\x0438\x0442 \x043a \x0441\x0435\x0431\x0435.\n\n\x0412\x0441\x0442\x0430\x0432\x0430\x0439, \x0431\x044b\x043b\x0438\x043d\x0443\x0448\x043a\x0430. \x041f\x043e\x043a\x0430 \x043f\x043e\x043c\x043d\x044f\x0442 \x2014 \x0436\x0438\x0432\x044b.";

/* --- Continue screen (profile found) --- */
static const wchar_t* H_CONT1   = L"\x041d\x0430\x0439\x0434\x0435\x043d \x043f\x0440\x043e\x0444\x0438\x043b\x044c \x0433\x0435\x0440\x043e\x044f:";
static const wchar_t* B_CONT    = L"\x041f\x0420\x041e\x0414\x041e\x041b\x0416\x0418\x0422\x042c \x0418\x0413\x0420\x0423";
static const wchar_t* B_NEW     = L"\x041d\x041e\x0412\x042b\x0419 \x0413\x0415\x0420\x041e\x0419";

/* --- World / village strings --- */
static const wchar_t* W_HINT    = L"\x041a\x043b\x0438\x043a \x041b\x041c\x041c \x2014 \x0438\x0434\x0442\x0438 \x043a \x0442\x043e\x0447\x043a\x0435. E \x2014 \x0433\x043e\x0432\x043e\x0440/\x043f\x043e\x0434\x0431\x043e\x0440. 1-4 \x2014 \x0443\x043c\x0435\x043d\x0438\x044f";
static const wchar_t* CAT_NAME  = L"\x041a\x043e\x0442 \x0423\x0447\x0451\x043d\x044b\x0439";
static const wchar_t* CAT_GREET = L"\x041c\x044f\x0443! \x0414\x043e\x0431\x0440\x043e \x043f\x043e\x0436\x0430\x043b\x043e\x0432\x0430\x0442\x044c, %ls, \x0431\x044b\x043b\x0438\x043d\x0443\x0448\x0430!";
static const wchar_t* CAT_QUEST = L"\x042f \x043a\x043e\x0442 \x0423\x0447\x0451\x043d\x044b\x0439, \x0445\x0440\x0430\x043d\x0438\x0442\x0435\x043b\x044c \x044d\x0442\x043e\x0439 \x0434\x0435\x0440\x0435\x0432\x043d\x0438. \x041f\x043e\x043a\x0430 \x043f\x0435\x0440\x0441\x0442\x043e \x043f\x043e\x0434 \x0434\x0443\x0431\x043e\x043c \x2014 \x0436\x0435\x043b\x0443\x0434\x0438 \x0434\x0443\x0431\x043e\x0432\x044b\x0435 \x0436\x0435\x043b\x0443\x0434\x0438! \x0421\x043e\x0431\x0435\x0440\x0438 3 \x0436\x0435\x043b\x0443\x0434\x044f \x0432\x043e\x0437\x043b\x0435 \x0434\x0443\x0431\x0430 (\x043f\x043e\x0434\x043e\x0439\x0434\x0438 \x043a \x043d\x0438\x043c \x0438 \x043d\x0430\x0436\x043c\x0438 \x0415).";
static const wchar_t* CAT_DONE  = L"\x041e\x0442\x043b\x0438\x0447\x043d\x043e, \x0431\x044b\x043b\x0438\x043d\x0443\x0448\x043a\x0430! \x0417\x0430\x043f\x0438\x0448\x0443 \x0442\x0432\x043e\x0451 \x0438\x043c\x044f \x0432 \x043b\x0435\x0442\x043e\x043f\x0438\x0441\x044c. \x041f\x0440\x043e\x0434\x043e\x043b\x0436\x0435\x043d\x0438\x0435 \x0441\x043b\x0435\x0434\x0443\x0435\x0442...";
static const wchar_t* Q_TITLE   = L"\x0417\x0430\x0434\x0430\x043d\x0438\x0435:";
static const wchar_t* Q_NONE    = L"\x041f\x043e\x0434\x043e\x0439\x0434\x0438 \x043a \x043a\x043e\x0442\x0443 \x0438 \x043d\x0430\x0436\x043c\x0438 E";
static const wchar_t* Q_STEP1   = L"\x041f\x043e\x043f\x0440\x0438\x0432\x0435\x0442\x0441\x0442\x0432\x043e\x0432\x0430\x0442\x044c \x0441 \x041a\x043e\x0442\x043e\x043c \x0423\x0447\x0451\x043d\x044b\x043c";
static const wchar_t* Q_STEP2   = L"\x0421\x043e\x0431\x0440\x0430\x0442\x044c \x0436\x0435\x043b\x0443\x0434\x0435\x0439 \x043f\x043e\x0434 \x0434\x0443\x0431\x043e\x043c";
static const wchar_t* Q_STEP3   = L"\x0412\x0435\x0440\x043d\x0443\x0442\x044c\x0441\x044f \x043a \x041a\x043e\x0442\x0443 \x0423\x0447\x0451\x043d\x043e\x043c\x0443";
static const wchar_t* Q_FIN     = L"\x0417\x0430\x0434\x0430\x043d\x0438\x0435 \x0432\x044b\x043f\x043e\x043b\x043d\x0435\x043d\x043e!";
static const wchar_t* T_ACORN   = L"\x0416\x0435\x043b\x0443\x0434\x044c";
static const wchar_t* T_OAK     = L"\x0414\x0443\x0431-\x043a\x0440\x0435\x0441\x0442";
static const wchar_t* NEAR_TALK = L"[E] \x041f\x043e\x0433\x043e\x0432\x043e\x0440\x0438\x0442\x044c";
static const wchar_t* NEAR_PICK = L"[E] \x0412\x0437\x044f\x0442\x044c";
static const wchar_t* SAVE_TAG  = L"\x25CF \x0441\x043e\x0445\x0440\x0430\x043d\x0435\x043d\x043e";

/* ------------------------------- State ----------------------------------- */
static int  g_screen   = SCR_LAUNCH;
static int  g_selected = -1;
static HWND g_hWnd     = NULL;
static HWND g_editNick = NULL;
static HFONT g_fBig, g_fMed, g_fSmall, g_fTitle;

/* forward decls */
static void DrawFrameAt(HDC hdc, RECT r, COLORREF c);
static void ShowDialog(const wchar_t* fmt, ...);
static void DrawAbilityBar(HDC hdc);
static int  BlockedAt(int nx, int ny);
static void CastAbility(HWND hwnd, int slot);
static void SaveProfile(void);
static wchar_t q_buf[128];

/* Player / world state (server-authoritative model mirrored locally) */
static wchar_t g_nick[64] = L"";
static int  g_px = 320, g_py = 380;          /* player pos in client units */
static int  g_hpCur = 100, g_hpMax = 100;
static int  g_questStep = 0;                  /* 0 none,1 greet,2 acorns,3 return,4 done */
static int  g_acorns = 0;
static int  g_catTalked = 0;
static int  g_dialogShown = 0;                /* dialog box visible */
static ULONGLONG g_dialogUntil = 0;
static wchar_t g_dialogText[512];
static ULONGLONG g_lastSave = 0;
static ULONGLONG g_saveFlashUntil = 0;        /* show "saved" indicator briefly */

/* Mouse-to-walk destination (click where to go) */
static int g_walkDestSet = 0;
static int g_walkX = 0, g_walkY = 0;

/* Energy / buffs for the ability hotbar (keys 1..4) */
static int  g_energyCur = 60, g_energyMax = 60;
static ULONGLONG g_buffUntil = 0;             /* damage buff expiry */
static ULONGLONG g_lastRegen = 0;             /* passive energy regen tick */

/* Acorns under the oak (fixed positions, respawn per session only) */
typedef struct { int x, y, taken; } Acorn;
static Acorn g_acorns_arr[3] = { {262,196,0}, {352,214,0}, {300,252,0} };

#define OAK_X 300
#define OAK_Y 190
#define CAT_X 392
#define CAT_Y 236
#define PICK_R 26
#define TALK_R 46
#define WALK_SPEED 5      /* px per tick (tick = 50 ms) -> ~100 px/s */
#define NABILITY 4

/* ----------------------------- Abilities ---------------------------------- */
enum { AB_DMG = 0, AB_HEAL, AB_BUFF, AB_PICK };
typedef struct {
    const wchar_t* name;
    const wchar_t* tag;   /* short effect line for the bar */
    int cost;             /* energy */
    int power;
    ULONGLONG cd;         /* cooldown ms; <1000 => "basic attack", no cooldown */
    int kind;
    ULONGLONG cdUntil;    /* runtime only */
    ULONGLONG lastCast;   /* runtime only */
} Ability;
static Ability g_ab[NABILITY];

static void BuildAbilities(void)
{
    int i, dmg = 12;
    for (i = 0; i < NABILITY; i++) { memset(&g_ab[i], 0, sizeof(Ability)); }
    g_ab[0].name = L"\x0423\x0434\x0430\x0440";            /* Удар (basic) */
    g_ab[0].tag  = L"-\x0416";                              /* -Ж */
    g_ab[0].kind = AB_DMG; g_ab[0].cost = 0; g_ab[0].cd = 400;
    g_ab[1].name = L"\x041a\x043b\x044f\x0442\x0432\x0430"; /* Клятва / Стрела / Гнев — class slot 2 */
    g_ab[1].kind = AB_DMG; g_ab[1].cd = 8000;
    g_ab[2].name = L""; g_ab[2].kind = AB_HEAL; g_ab[2].cd = 15000;
    g_ab[3].name = L"\x0417\x043e\x0440\x044e";            /* Зорю (universal utility: pick acorns at range) */
    g_ab[3].tag  = L"+\x0416\x0435\x043b";                 /* +Жел */
    g_ab[3].kind = AB_PICK; g_ab[3].cost = 10; g_ab[3].power = 0; g_ab[3].cd = 3000;
    switch (g_selected) {
        case 0: /* Богатырь */
            dmg = 18;
            g_ab[1].tag = L"-27 \x043f\x043e \x0432\x0441\x0435\x043c"; /* AoE flavor */
            g_ab[1].cost = 20; g_ab[1].power = 27;
            g_ab[2].name = L"\x041a\x043b\x044f\x0442\x0432\x0430 \x0411\x043e\x0433\x0430"; /* Клятва Бога */
            g_ab[2].tag  = L"+40 \x0416";
            g_ab[2].cost = 25; g_ab[2].power = 40;
            break;
        case 1: /* Стрелок */
            dmg = 24;
            g_ab[1].name = L"\x0422\x043e\x0447\x043d\x044b\x0439 \x0412\x044b\x0441\x0442\x0440\x0435\x043b"; /* Точный Выстрел */
            g_ab[1].tag  = L"-36";
            g_ab[1].cost = 15; g_ab[1].power = 36;
            g_ab[2].name = L"\x0412\x0435\x0442\x0435\x0440";  /* Ветер: buff +50% dmg */
            g_ab[2].tag  = L"+50% \x0443\x0440\x043e\x043d";
            g_ab[2].kind = AB_BUFF; g_ab[2].cost = 20; g_ab[2].power = 0; g_ab[2].cd = 20000;
            break;
        case 2: /* Волхв */
            dmg = 14;
            g_ab[1].name = L"\x041e\x0433\x043d\x0435\x043d\x044c"; /* Огонёк */
            g_ab[1].tag  = L"-30";
            g_ab[1].cost = 25; g_ab[1].power = 30;
            g_ab[2].name = L"\x0427\x0443\x0440\x0430";     /* Чур: heal + shield flavor */
            g_ab[2].tag  = L"+30 \x0416";
            g_ab[2].cost = 30; g_ab[2].power = 30;
            break;
        default: break;
    }
    g_ab[0].power = dmg;
    {
        static wchar_t t0[8];
        swprintf(t0, 8, L"-%d", dmg);
        g_ab[0].tag = t0;
    }
}

/* --------------------------- File DB (real time) ------------------------- */
static void ProfilePathW(wchar_t* out, size_t cch)
{
    wchar_t* dot;
    GetModuleFileNameW(NULL, out, (DWORD)cch);
    dot = wcsrchr(out, L'.');
    if (dot) wcscpy(dot, L"_profile.json");
    else     wcscat(out, L"_profile.json");
}

/* Atomic save: write temp then MoveFileEx replace => never corrupts on crash */
static void SaveProfile(void)
{
    wchar_t wpath[MAX_PATH], wtmp[MAX_PATH];
    if (g_editNick && g_screen == SCR_SELECT)
        GetWindowTextW(g_editNick, g_nick, 63); /* keep live nickname */
    char apath[MAX_PATH*3], atmp[MAX_PATH*3], nutf[256];
    FILE* f;
    time_t t = time(NULL);
    struct tm tmv;
    char stamp[32];

    ProfilePathW(wpath, MAX_PATH);
    lstrcpynW(wtmp, wpath, MAX_PATH);
    wcscat(wtmp, L".tmp");

    WideCharToMultiByte(CP_UTF8, 0, wpath, -1, apath, sizeof(apath), NULL, NULL);
    WideCharToMultiByte(CP_UTF8, 0, wtmp,  -1, atmp,  sizeof(atmp),  NULL, NULL);
    WideCharToMultiByte(CP_UTF8, 0, g_nick, -1, nutf, sizeof(nutf), NULL, NULL);

#ifdef _MSC_VER
    localtime_s(&tmv, &t);
#else
    tmv = *localtime(&t);
#endif
    strftime(stamp, sizeof(stamp), "%Y-%m-%dT%H:%M:%S", &tmv);

    f = fopen(atmp, "w");
    if (!f) return;
    fprintf(f,
        "{\n"
        "  \"version\": 3,\n"
        "  \"updatedAt\": \"%s\",\n"
        "  \"nickname\": \"%s\",\n"
        "  \"classId\": %d,\n"
        "  \"hp\": %d,\n"
        "  \"hpMax\": %d,\n"
        "  \"energy\": %d,\n"
        "  \"pos\": { \"x\": %d, \"y\": %d },\n"
        "  \"quest\": { \"step\": %d, \"acorns\": %d, \"catTalked\": %s },\n"
        "  \"acornTaken\": [%d, %d, %d]\n"
        "}\n",
        stamp, nutf, g_selected, g_hpCur, g_hpMax, g_energyCur, g_px, g_py,
        g_questStep, g_acorns, g_catTalked ? "true" : "false",
        g_acorns_arr[0].taken, g_acorns_arr[1].taken, g_acorns_arr[2].taken);
    fclose(f);

    /* atomic replace: MoveFileEx(REPLACE_EXISTING) without prior delete */
    if (!MoveFileExA(atmp, apath, MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH)) {
        remove(atmp);
        rename(atmp, apath);
    }
    g_lastSave = GetTickCount64();
    g_saveFlashUntil = g_lastSave + 1500;
}

/* Minimal JSON reader for our own format (tolerant of key order) */
static int JsonGetInt(const char* js, const char* key, int def)
{
    char pat[64];
    const char* p;
    snprintf(pat, sizeof(pat), "\"%s\"", key);
    p = strstr(js, pat);
    if (!p) return def;
    p += strlen(pat);
    p = strchr(p, ':');
    if (!p) return def;
    return atoi(p + 1);
}
static void JsonGetStr(const char* js, const char* key, wchar_t* out, size_t cch, const wchar_t* def)
{
    char pat[64], buf[256];
    const char* p, *s, *e;
    int n;
    snprintf(pat, sizeof(pat), "\"%s\"", key);
    p = strstr(js, pat);
    wcscpy(out, def);
    if (!p) return;
    p = strchr(p + strlen(pat), '"');
    if (!p) return;
    s = p + 1;
    e = strchr(s, '"');
    if (!e) return;
    n = (int)(e - s);
    if (n > 250) n = 250;
    memcpy(buf, s, n);
    buf[n] = 0;
    MultiByteToWideChar(CP_UTF8, 0, buf, -1, out, (int)cch);
}

static int LoadProfile(void) /* returns 1 if a valid profile was loaded */
{
    wchar_t wpath[MAX_PATH];
    char apath[MAX_PATH*3];
    FILE* f;
    long sz;
    char* buf;
    int ok = 0, i;

    ProfilePathW(wpath, MAX_PATH);
    WideCharToMultiByte(CP_UTF8, 0, wpath, -1, apath, sizeof(apath), NULL, NULL);
    f = fopen(apath, "rb");
    if (!f) return 0;
    fseek(f, 0, SEEK_END); sz = ftell(f); fseek(f, 0, SEEK_SET);
    if (sz <= 0 || sz > 65536) { fclose(f); return 0; }
    buf = (char*)malloc(sz + 1);
    if (!buf) { fclose(f); return 0; }
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return 0; }
    buf[sz] = 0;
    fclose(f);

    if (strstr(buf, "\"classId\"")) {
        g_selected   = JsonGetInt(buf, "classId", -1);
        g_hpMax      = JsonGetInt(buf, "hpMax", g_class[g_selected >= 0 && g_selected < NCLASS ? g_selected : 0].hp);
        g_hpCur      = JsonGetInt(buf, "hp", g_hpMax);
        g_energyMax  = (g_selected >= 0 && g_selected < NCLASS) ? g_class[g_selected].energy : 60;
        g_energyCur  = JsonGetInt(buf, "energy", g_energyMax);
        if (g_energyCur > g_energyMax) g_energyCur = g_energyMax;
        g_px         = JsonGetInt(buf, "x", 320);
        g_py         = JsonGetInt(buf, "y", 380);
        g_questStep  = JsonGetInt(buf, "step", 0);
        g_acorns     = JsonGetInt(buf, "acorns", 0);
        g_catTalked  = strstr(buf, "\"catTalked\": true") ? 1 : 0;
        for (i = 0; i < 3; i++) g_acorns_arr[i].taken = (i < g_acorns) ? 1 : 0;
        JsonGetStr(buf, "nickname", g_nick, 64, L"");
        if (g_selected >= 0 && g_selected < NCLASS && wcslen(g_nick) > 0) ok = 1;
    }
    free(buf);
    return ok;
}

/* ------------------------------ Rendering -------------------------------- */
static void DrawFrame(HDC hdc, RECT r, COLORREF c)
{
    HPEN pen = CreatePen(PS_SOLID, 2, c);
    HPEN old = (HPEN)SelectObject(hdc, pen);
    HBRUSH ob = (HBRUSH)SelectObject(hdc, GetStockObject(NULL_BRUSH));
    Rectangle(hdc, r.left, r.top, r.right, r.bottom);
    SelectObject(hdc, old);
    SelectObject(hdc, ob);
    DeleteObject(pen);
}

static void TextC(HDC hdc, int x, int y, const wchar_t* s, COLORREF c, HFONT f, int center)
{
    HFONT old = (HFONT)SelectObject(hdc, f);
    SetTextColor(hdc, c);
    SetBkMode(hdc, TRANSPARENT);
    if (center) {
        SIZE sz; GetTextExtentPoint32W(hdc, s, (int)wcslen(s), &sz);
        TextOutW(hdc, x - sz.cx / 2, y, s, (int)wcslen(s));
    } else {
        TextOutW(hdc, x, y, s, (int)wcslen(s));
    }
    SelectObject(hdc, old);
}

static void FillCircle(HDC hdc, int cx, int cy, int r, COLORREF c)
{
    HBRUSH b = CreateSolidBrush(c);
    HPEN p = (HPEN)GetStockObject(NULL_PEN);
    HPEN op = (HPEN)SelectObject(hdc, p);
    HBRUSH ob = (HBRUSH)SelectObject(hdc, b);
    Ellipse(hdc, cx - r, cy - r, cx + r, cy + r);
    SelectObject(hdc, op);
    SelectObject(hdc, ob);
    DeleteObject(b);
}

static void FillEllipse(HDC hdc, int cx, int cy, int rx, int ry, COLORREF c)
{
    HBRUSH b = CreateSolidBrush(c);
    HPEN op = (HPEN)SelectObject(hdc, (HPEN)GetStockObject(NULL_PEN));
    HBRUSH ob = (HBRUSH)SelectObject(hdc, b);
    Ellipse(hdc, cx - rx, cy - ry, cx + rx, cy + ry);
    SelectObject(hdc, op);
    SelectObject(hdc, ob);
    DeleteObject(b);
}

static void RectFill(HDC hdc, int x, int y, int w, int h, COLORREF c)
{
    HBRUSH b = CreateSolidBrush(c);
    RECT r = { x, y, x + w, y + h };
    FillRect(hdc, &r, b);
    DeleteObject(b);
}

static void Line(HDC hdc, int x1, int y1, int x2, int y2, COLORREF c, int wide)
{
    HPEN p = CreatePen(PS_SOLID, wide, c);
    HPEN o = (HPEN)SelectObject(hdc, p);
    MoveToEx(hdc, x1, y1, NULL);
    LineTo(hdc, x2, y2);
    SelectObject(hdc, o);
    DeleteObject(p);
}

/* ------------ Village drawing (logic-free, pure visual layer) ------------- */
static void DrawVillage(HDC hdc)
{
    int i;
    /* sky-ish ground palette: meadow */
    RectFill(hdc, 0, 0, WIN_W, WIN_H, RGB(0x6E,0x8F,0x4E));            /* grass */
    /* dirt road across the village */
    RectFill(hdc, 0, 300, WIN_W, 46, RGB(0xA8,0x8A,0x5C));
    for (i = 0; i < 12; i++)
        FillCircle(hdc, 20 + i * 55, 322 + ((i * 37) % 14), 2, RGB(0x8A,0x70,0x48));

    /* fence along the top */
    for (i = 0; i < 16; i++) {
        int fx = 10 + i * 40;
        RectFill(hdc, fx, 58, 5, 26, RGB(0x8B,0x6B,0x3F));
    }
    RectFill(hdc, 0, 66, WIN_W, 4, RGB(0x9A,0x78,0x48));
    RectFill(hdc, 0, 78, WIN_W, 3, RGB(0x9A,0x78,0x48));

    /* izbas (huts) left and right */
    /* hut 1 */
    RectFill(hdc, 40, 120, 96, 70, RGB(0xB5,0x8A,0x4E));
    RectFill(hdc, 40, 120, 96, 8,  RGB(0x8B,0x6B,0x3F));
    /* roof */
    { POINT pts[3] = {{30,122},{146,122},{88,86}}; HRGN rg = CreatePolygonRgn(pts,3,WINDING); 
      HBRUSH b = CreateSolidBrush(RGB(0x6B,0x3F,0x2A)); FillRgn(hdc,rg,b); DeleteObject(b); DeleteObject(rg); }
    RectFill(hdc, 60, 148, 24, 30, RGB(0x5A,0x3A,0x1E));               /* door */
    RectFill(hdc, 104, 140, 20, 18, RGB(0x9F,0xD6,0xE8));                    /* window */
    Line(hdc, 114, 140, 114, 158, RGB(0x5A,0x3A,0x1E), 1);
    Line(hdc, 104, 149, 124, 149, RGB(0x5A,0x3A,0x1E), 1);

    /* hut 2 */
    RectFill(hdc, 500, 118, 100, 72, RGB(0xC0,0x96,0x58));
    { POINT pts[3] = {{490,120},{610,120},{550,84}}; HRGN rg = CreatePolygonRgn(pts,3,WINDING);
      HBRUSH b = CreateSolidBrush(RGB(0x6B,0x3F,0x2A)); FillRgn(hdc,rg,b); DeleteObject(b); DeleteObject(rg); }
    RectFill(hdc, 520, 150, 24, 32, RGB(0x5A,0x3A,0x1E));
    RectFill(hdc, 566, 140, 20, 18, RGB(0x9F,0xD6,0xE8));
    Line(hdc, 576, 140, 576, 158, RGB(0x5A,0x3A,0x1E), 1);
    Line(hdc, 566, 149, 586, 149, RGB(0x5A,0x3A,0x1E), 1);

    /* well */
    RectFill(hdc, 150, 250, 40, 26, RGB(0x77,0x77,0x77));
    Line(hdc, 152, 250, 152, 232, RGB(0x6B,0x3F,0x2A), 3);
    Line(hdc, 188, 250, 188, 232, RGB(0x6B,0x3F,0x2A), 3);
    { POINT pts[3] = {{146,234},{194,234},{170,220}}; HRGN rg = CreatePolygonRgn(pts,3,WINDING);
      HBRUSH b = CreateSolidBrush(RGB(0x8B,0x3A,0x2A)); FillRgn(hdc,rg,b); DeleteObject(b); DeleteObject(rg); }

    /* ---- Oak tree in the center ---- */
    /* trunk */
    RectFill(hdc, OAK_X - 10, OAK_Y + 6, 20, 40, RGB(0x6B,0x4A,0x24));
    Line(hdc, OAK_X - 10, OAK_Y + 20, OAK_X - 26, OAK_Y + 4, RGB(0x6B,0x4A,0x24), 5);
    Line(hdc, OAK_X + 10, OAK_Y + 26, OAK_X + 28, OAK_Y + 10, RGB(0x6B,0x4A,0x24), 5);
    /* crown: layered circles */
    FillCircle(hdc, OAK_X,      OAK_Y - 26, 34, RGB(0x2F,0x5A,0x2B));
    FillCircle(hdc, OAK_X - 30, OAK_Y - 10, 26, RGB(0x38,0x66,0x30));
    FillCircle(hdc, OAK_X + 30, OAK_Y - 10, 26, RGB(0x38,0x66,0x30));
    FillCircle(hdc, OAK_X - 12, OAK_Y - 40, 22, RGB(0x44,0x74,0x38));
    FillCircle(hdc, OAK_X + 14, OAK_Y - 40, 22, RGB(0x44,0x74,0x38));
    FillCircle(hdc, OAK_X,      OAK_Y - 14, 30, RGB(0x3E,0x6E,0x34));
    TextC(hdc, OAK_X, OAK_Y + 50, T_OAK, RGB(0xF0,0xEA,0xD0), g_fSmall, 1);

    /* ---- acorns under the oak ---- */
    for (i = 0; i < 3; i++) {
        if (g_acorns_arr[i].taken) continue;
        /* nut */
        FillCircle(hdc, g_acorns_arr[i].x, g_acorns_arr[i].y, 6, RGB(0xC8,0x8A,0x3E));
        /* cap */
        FillEllipse(hdc, g_acorns_arr[i].x, g_acorns_arr[i].y - 5, 7, 4, RGB(0x6B,0x4A,0x24));
    }

    /* ---- Cat the Scholar ---- */
    /* body */
    FillEllipse(hdc, CAT_X, CAT_Y + 8, 13, 16, RGB(0x59,0x59,0x63));
    /* head */
    FillCircle(hdc, CAT_X, CAT_Y - 14, 11, RGB(0x66,0x66,0x70));
    /* tail */
    Line(hdc, CAT_X + 12, CAT_Y + 16, CAT_X + 22, CAT_Y - 2, RGB(0x59,0x59,0x63), 4);
}

/* NOTE: the block above intentionally avoids complex polygon code; cat ears
 * are drawn in PaintWorld for clarity. */

static void DrawCatExtras(HDC hdc)
{
    /* ears */
    HBRUSH b = CreateSolidBrush(RGB(0x66,0x66,0x70));
    HPEN   p = (HPEN)GetStockObject(NULL_PEN);
    HPEN   op = (HPEN)SelectObject(hdc, p);
    HBRUSH ob = (HBRUSH)SelectObject(hdc, b);
    POINT e1[3] = {{CAT_X-11,CAT_Y-20},{CAT_X-7,CAT_Y-32},{CAT_X-1,CAT_Y-22}};
    POINT e2[3] = {{CAT_X+11,CAT_Y-20},{CAT_X+7,CAT_Y-32},{CAT_X+1,CAT_Y-22}};
    Polygon(hdc, e1, 3);
    Polygon(hdc, e2, 3);
    SelectObject(hdc, ob); DeleteObject(b); SelectObject(hdc, op);

    /* eyes */
    FillCircle(hdc, CAT_X - 4, CAT_Y - 15, 2, RGB(0xFF,0xE9,0x7A));
    FillCircle(hdc, CAT_X + 4, CAT_Y - 15, 2, RGB(0xFF,0xE9,0x7A));

    /* spectacles — he is a scholar */
    HPEN gp = CreatePen(PS_SOLID, 1, RGB(0xE8,0xE0,0xB0));
    HPEN go = (HPEN)SelectObject(hdc, gp);
    SelectObject(hdc, GetStockObject(NULL_BRUSH));
    Ellipse(hdc, CAT_X - 8, CAT_Y - 19, CAT_X - 1, CAT_Y - 12);
    Ellipse(hdc, CAT_X + 1, CAT_Y - 19, CAT_X + 8, CAT_Y - 12);
    Line(hdc, CAT_X - 1, CAT_Y - 16, CAT_X + 1, CAT_Y - 16, RGB(0xE8,0xE0,0xB0), 1);
    SelectObject(hdc, go); DeleteObject(gp);

    /* little scroll in paws */
    RectFill(hdc, CAT_X - 6, CAT_Y + 6, 12, 8, RGB(0xF2,0xE7,0xC8));
    Line(hdc, CAT_X - 6, CAT_Y + 6, CAT_X - 6, CAT_Y + 14, RGB(0xB0,0x9A,0x60), 2);
    Line(hdc, CAT_X + 6, CAT_Y + 6, CAT_X + 6, CAT_Y + 14, RGB(0xB0,0x9A,0x60), 2);

    TextC(hdc, CAT_X, CAT_Y + 30, CAT_NAME, RGB(0xFF,0xF3,0xC0), g_fSmall, 1);
}

static void DrawHero(HDC hdc)
{
    COLORREF col = (g_selected >= 0 && g_selected < NCLASS) ? g_class[g_selected].color : RGB(60,60,120);
    /* shadow */
    FillEllipse(hdc, g_px, g_py + 14, 10, 4, RGB(0x40,0x55,0x35));
    /* body */
    FillEllipse(hdc, g_px, g_py + 2, 8, 11, col);
    /* head */
    FillCircle(hdc, g_px, g_py - 14, 7, RGB(0xE8,0xC8,0x9A));
    TextC(hdc, g_px, g_py + 20, g_nick, RGB(0xFF,0xFF,0xFF), g_fSmall, 1);
}

static void DrawDialogBox(HDC hdc)
{
    RECT r = { 24, 356, 616, 448 };
    HPEN pen;
    if (!g_dialogShown) return;
    pen = CreatePen(PS_SOLID, 2, RGB(0xE8,0xD8,0x9A));
    SelectObject(hdc, pen);
    { HBRUSH b = CreateSolidBrush(RGB(0x24,0x1E,0x14));
      HBRUSH ob=(HBRUSH)SelectObject(hdc,b);
      Rectangle(hdc, r.left, r.top, r.right, r.bottom);
      SelectObject(hdc, ob); DeleteObject(b); }
    DeleteObject(pen);
    TextC(hdc, r.left + 12, r.top + 8, CAT_NAME, RGB(0xFF,0xE9,0x7A), g_fMed, 0);
    {
        /* naive word-wrap into 2 lines */
        HDC mdc = hdc; HFONT of = SelectObject(mdc, g_fSmall);
        wchar_t line1[256] = L"", line2[256] = L"";
        const wchar_t* s = g_dialogText; int w, maxw = 560, cur = 0; int l2 = 0;
        const wchar_t* start = s;
        while (*s) {
            const wchar_t* sp = wcschr(s, L' ');
            int len = sp ? (int)(sp - s) : (int)wcslen(s);
            SIZE sz; GetTextExtentPoint32W(mdc, start, (int)(s + len - start), &sz);
            if (sz.cx > maxw) {
                if (!l2) { wcsncpy(line1, start, s - start); line1[s-start]=0; l2 = 1; }
                start = s;
            }
            s += len; if (*s == L' ') s++;
            (void)cur; (void)w;
        }
        if (l2) { SIZE sz; GetTextExtentPoint32W(mdc, start, (int)wcslen(start), &sz);
                  wcsncpy(line2, start, 255); line2[255]=0; }
        else    { wcsncpy(line1, start, 255); line1[255]=0; }
        SelectObject(mdc, of);
        TextC(hdc, r.left + 12, r.top + 30, line1, RGB(0xF0,0xEA,0xD0), g_fSmall, 0);
        if (line2[0]) TextC(hdc, r.left + 12, r.top + 48, line2, RGB(0xF0,0xEA,0xD0), g_fSmall, 0);
    }
    TextC(hdc, r.right - 120, r.bottom - 20, L"[E]/\x041a\x043b\x0438\x043a \x2014 \x0434\x0430\x043b\x044c\x0448\x0435", RGB(0xB0,0xA8,0x88), g_fSmall, 0);
}

static void DrawQuestTracker(HDC hdc)
{
    wchar_t q[128];
    const wchar_t* st;
    RECT r = { 24, 12, 616, 44 };
    HBRUSH b = CreateSolidBrush(RGB(0x1E,0x18,0x10));
    FillRect(hdc, &r, b); DeleteObject(b);
    DrawFrame(hdc, r, RGB(0x8A,0x74,0x40));

    switch (g_questStep) {
        case 0: st = Q_NONE; break;
        case 1: st = Q_STEP1; break;
        case 2: swprintf(q, 128, L"%ls (%d/3)", Q_STEP2, g_acorns); st = q; break;
        case 3: st = Q_STEP3; break;
        default: st = Q_FIN; break;
    }
    TextC(hdc, 34, 18, Q_TITLE, RGB(0xFF,0xE9,0x7A), g_fSmall, 0);
    { SIZE sz; HFONT of = SelectObject(hdc, g_fSmall); GetTextExtentPoint32W(hdc, Q_TITLE, (int)wcslen(Q_TITLE), &sz); SelectObject(hdc, of);
      TextC(hdc, 34 + sz.cx + 10, 18, st, RGB(0xF0,0xEA,0xD0), g_fSmall, 0); }

    if (GetTickCount64() < g_saveFlashUntil)
        TextC(hdc, 560, 18, SAVE_TAG, RGB(0x7A,0xE0,0x7A), g_fSmall, 0);
}

static void PaintWorld(HDC hdc)
{
    int nearestPick = -1, dx, dy;
    double d;
    int i;
    int canTalk;

    DrawVillage(hdc);
    DrawCatExtras(hdc);

    /* find nearest untaken acorn */
    { double bd = 1e18;
      for (i = 0; i < 3; i++) {
          if (g_acorns_arr[i].taken) continue;
          dx = g_px - g_acorns_arr[i].x; dy = g_py - g_acorns_arr[i].y;
          d = sqrt((double)(dx*dx + dy*dy));
          if (d < PICK_R && d < bd) { bd = d; nearestPick = i; }
      }
    }

    DrawHero(hdc);

    /* interaction prompt */
    canTalk = 0;
    { dx = g_px - CAT_X; dy = g_py - CAT_Y; if (sqrt((double)(dx*dx+dy*dy)) < TALK_R) canTalk = 1; }
    if (!g_dialogShown) {
        if (canTalk)
            TextC(hdc, CAT_X, CAT_Y - 46, NEAR_TALK, RGB(0xFF,0xF3,0xC0), g_fMed, 1);
        else if (nearestPick >= 0)
            TextC(hdc, g_acorns_arr[nearestPick].x, g_acorns_arr[nearestPick].y - 20, NEAR_PICK, RGB(0xFF,0xF3,0xC0), g_fMed, 1);
    }

    /* HUD: class + hp bar */
    {
        int bx = 24, by = 452;
        const wchar_t* cname = (g_selected>=0&&g_selected<NCLASS)? g_class[g_selected].name : L"?";
        TextC(hdc, bx, by - 2, cname, RGB(0xFF,0xFF,0xFF), g_fSmall, 0);
        RectFill(hdc, bx + 70, by, 120, 10, RGB(0x33,0x1a,0x1a));
        RectFill(hdc, bx + 70, by, (int)(120.0 * g_hpCur / (g_hpMax?g_hpMax:1)), 10, RGB(0xC0,0x3A,0x3A));
        DrawFrame(hdc, (RECT){bx+70,by,bx+190,by+10}, RGB(0x88,0x66,0x44));
        /* energy bar under HP */
        RectFill(hdc, bx + 70, by + 12, 120, 6, RGB(0x14,0x20,0x38));
        RectFill(hdc, bx + 70, by + 12, (int)(120.0 * g_energyCur / (g_energyMax?g_energyMax:1)), 6, RGB(0x3A,0x7A,0xC8));
        swprintf(q_buf, sizeof(q_buf)/sizeof(wchar_t), L"%ls: %d/3", T_ACORN, g_acorns);
        TextC(hdc, 240, by - 2, q_buf, RGB(0xFF,0xE9,0x7A), g_fSmall, 0);
    }
    DrawAbilityBar(hdc);
    if (GetTickCount64() < g_buffUntil)
        TextC(hdc, 250, 432, L"\x0411\x0430\x0444\x0444: +50% \x0443\x0440\x043e\x043d", RGB(0x9A,0xE0,0x9A), g_fSmall, 0);
    TextC(hdc, WIN_W/2, 424, W_HINT, RGB(0xD8,0xD0,0xB8), g_fSmall, 1);

    DrawDialogBox(hdc);
    DrawQuestTracker(hdc);
}

static void ShowDialog(const wchar_t* fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    _vsnwprintf(g_dialogText, 511, fmt, ap);
    va_end(ap);
    g_dialogText[511] = 0;
    g_dialogShown = 1;
    g_dialogUntil = GetTickCount64() + 6000; /* auto-hide after 6s */
}

/* ---------------------------- UI screens ---------------------------------- */
static void LayoutForScreen(HWND hwnd);

static void PaintLaunch(HWND hwnd, HDC hdc)
{
    RectFill(hdc, 0, 0, WIN_W, WIN_H, RGB(0x10,0x14,0x20));
    /* stars */
    { int i; for (i = 0; i < 40; i++) {
        int sx = (i * 97 + 31) % WIN_W, sy = (i * 53 + 17) % 200;
        RectFill(hdc, sx, sy, 2, 2, RGB(0x9A,0xA8,0xC8)); } }
    /* fire circle */
    FillCircle(hdc, WIN_W/2, 150, 60, RGB(0x2A,0x24,0x18));
    DrawFrame(hdc, (RECT){WIN_W/2-60,90,WIN_W/2+60,210}, RGB(0xC8,0x9A,0x3E));
    TextC(hdc, WIN_W/2, 128, S_LOGO, RGB(0xE8,0xC8,0x5A), g_fTitle, 1);
    TextC(hdc, WIN_W/2, 232, S_SLOGAN, RGB(0xC8,0xB8,0x8A), g_fMed, 1);
    TextC(hdc, WIN_W/2, 262, S_SUBT, RGB(0x8A,0x90,0xA0), g_fSmall, 1);
    (void)hwnd;
}

static void PaintSelect(HWND hwnd, HDC hdc)
{
    int i;
    (void)hwnd;
    RectFill(hdc, 0, 0, WIN_W, WIN_H, RGB(0x12,0x16,0x22));
    TextC(hdc, WIN_W/2, 10, L"\x0412\x044b\x0431\x0435\x0440\x0438 \x0431\x044b\x043b\x0438\x043d\x0443 \x2014 \x0433\x0435\x0440\x043e\x044f \x043f\x043e \x0441\x0435\x0440\x0434\x0446\x0443", RGB(0xE8,0xC8,0x5A), g_fMed, 1);
    for (i = 0; i < NCLASS; i++) {
        RECT r = { 12 + i * 208, 44, 12 + i * 208 + 200, 300 };
        HBRUSH b = CreateSolidBrush(g_selected == i ? RGB(0x2A,0x34,0x50) : RGB(0x1A,0x1E,0x2C));
        FillRect(hdc, &r, b); DeleteObject(b);
        DrawFrame(hdc, r, g_class[i].color);
        TextC(hdc, (r.left+r.right)/2, 52, g_class[i].name, RGB(0xFF,0xFF,0xFF), g_fMed, 1);
        TextC(hdc, (r.left+r.right)/2, 76, g_class[i].tag, g_class[i].color==RGB(0x2F,0x3A,0x8B)?RGB(0x9A,0xAA,0xFF):RGB(0xC8,0xC8,0xC8), g_fSmall, 1);
        {
            /* wrap description manually: split on spaces into 4 lines */
            HDC m = hdc; HFONT of = SelectObject(m, g_fSmall);
            const wchar_t* words = g_class[i].desc;
            wchar_t line[128]; wchar_t out[256]; int oy = 100; out[0]=0;
            const wchar_t* s = words; line[0]=0;
            while (1) {
                const wchar_t* sp = wcschr(s, L' ');
                int wl = sp ? (int)(sp - s) : (int)wcslen(s);
                SIZE sz; wchar_t trial[160];
                swprintf(trial, 160, L"%ls %.*ls", line, wl, s);
                GetTextExtentPoint32W(m, trial, (int)wcslen(trial), &sz);
                if (sz.cx > 190 && line[0]) {
                    lstrcpynW(out + wcslen(out), line, 128); lstrcpynW(out + wcslen(out), L"\n", 2);
                    wcscpy(line, L"");
                }
                if (!line[0]) { wcsncpy(line, s, wl); line[wl]=0; }
                else { wchar_t t2[160]; swprintf(t2,160,L"%ls %.*ls",line,wl,s); wcscpy(line,t2);}
                if (!sp) break;
                s = sp + 1;
            }
            if (line[0]) { lstrcpynW(out + wcslen(out), line, 128); }
            SelectObject(m, of);
            { wchar_t* ctx = NULL; wchar_t* ln = wcstok_s(out, L"\n", &ctx);
              while (ln) { TextC(hdc, r.left + 10, oy, ln, RGB(0xC8,0xC8,0xD8), g_fSmall, 0); oy += 16; ln = wcstok_s(NULL, L"\n", &ctx); } }
        }
        {
            wchar_t stats[96];
            swprintf(stats, 96, L"\x0416\x0438\x0437\x043d\x044c %d \x2022 \x0423\x0440\x043e\x043d %d \x2022 \x042d\x043d %d", g_class[i].hp, g_class[i].dmg, g_class[i].energy);
            TextC(hdc, (r.left+r.right)/2, 276, stats, RGB(0x9A,0xE0,0x9A), g_fSmall, 1);
        }
    }
    TextC(hdc, 20, 312, L"\x0418\x043c\x044f \x0433\x0435\x0440\x043e\x044f:", RGB(0xE0,0xE0,0xE0), g_fMed, 0);
}

static void PaintContinue(HWND hwnd, HDC hdc)
{
    wchar_t info[160];
    const wchar_t* cname = (g_selected>=0&&g_selected<NCLASS)? g_class[g_selected].name : L"?";
    (void)hwnd;
    RectFill(hdc, 0, 0, WIN_W, WIN_H, RGB(0x10,0x14,0x20));
    TextC(hdc, WIN_W/2, 120, H_CONT1, RGB(0xE8,0xC8,0x5A), g_fMed, 1);
    swprintf(info, 160, L"%ls \x2014 %ls", g_nick, cname);
    TextC(hdc, WIN_W/2, 160, info, RGB(0xFF,0xFF,0xFF), g_fBig, 1);
    swprintf(info, 160, L"\x0416\x0438\x0437\x043d\x044c: %d/%d \x2022 \x0416\x0435\x043b\x0443\x0434\x0435\x0439: %d", g_hpCur, g_hpMax, g_acorns);
    TextC(hdc, WIN_W/2, 196, info, RGB(0x9A,0xE0,0x9A), g_fSmall, 1);
}

static void OnPaint(HWND hwnd)
{
    PAINTSTRUCT ps;
    HDC hdc = BeginPaint(hwnd, &ps);
    /* double buffer */
    HDC mem = CreateCompatibleDC(hdc);
    HBITMAP bmp = CreateCompatibleBitmap(hdc, WIN_W, WIN_H);
    HBITMAP old = (HBITMAP)SelectObject(mem, bmp);

    switch (g_screen) {
        case SCR_LAUNCH:   PaintLaunch(hwnd, mem);  break;
        case SCR_SELECT:   PaintSelect(hwnd, mem);  break;
        case SCR_LORE:
            RectFill(mem, 0, 0, WIN_W, WIN_H, RGB(0x0C,0x10,0x1A));
            TextC(mem, WIN_W/2, 40, L"\x041f\x0440\x0435\x0434\x0430\x043d\x0438\x0435", RGB(0xE8,0xC8,0x5A), g_fMed, 1);
            TextC(mem, 60, 90, LORE_TEXT, RGB(0xC8,0xC8,0xD8), g_fSmall, 0);
            break;
        case SCR_CONTINUE: PaintContinue(hwnd, mem); break;
        case SCR_WORLD:    PaintWorld(mem);          break;
    }
    BitBlt(hdc, 0, 0, WIN_W, WIN_H, mem, 0, 0, SRCCOPY);
    SelectObject(mem, old);
    DeleteObject(bmp);
    DeleteDC(mem);
    EndPaint(hwnd, &ps);
}

/* --------------------------- Controls per screen -------------------------- */
static HWND mkbtn(HWND parent, const wchar_t* text, int id, int x, int y, int w, int h)
{
    return CreateWindowExW(0, L"BUTTON", text, WS_CHILD | WS_VISIBLE | BS_OWNERDRAW,
                           x, y, w, h, parent, (HMENU)(INT_PTR)id,
                           GetModuleHandle(NULL), NULL);
}
static BOOL CALLBACK DestroyChildCb(HWND c, LPARAM l) { (void)l; DestroyWindow(c); return TRUE; }

static void LayoutForScreen(HWND hwnd)
{
    /* remove all controls, recreate per screen */
    EnumChildWindows(hwnd, DestroyChildCb, 0);
    g_editNick = NULL;

    switch (g_screen) {
        case SCR_LAUNCH:
            mkbtn(hwnd, B_START, IDC_BTN_START, 220, 320, 200, 40);
            mkbtn(hwnd, B_LORE,  IDC_BTN_LORE,  220, 370, 200, 34);
            mkbtn(hwnd, B_EXIT,  IDC_BTN_QUIT,  220, 414, 200, 34);
            break;
        case SCR_SELECT: {
            int i;
            for (i = 0; i < NCLASS; i++) mkbtn(hwnd, L"", IDC_CARD_0 + i, 12 + i * 208, 44, 200, 256);
            g_editNick = CreateWindowExW(0, L"EDIT", L"", WS_CHILD | WS_VISIBLE | WS_BORDER | ES_AUTOHSCROLL,
                                         130, 310, 300, 24, hwnd, (HMENU)(INT_PTR)IDC_EDT_NICK,
                                         GetModuleHandle(NULL), NULL);
            SendMessageW(g_editNick, WM_SETFONT, (WPARAM)g_fMed, TRUE);
            if (g_nick[0]) SetWindowTextW(g_editNick, g_nick);
            mkbtn(hwnd, B_CHOOSE, IDC_BTN_CHOOSE, 220, 348, 200, 36);
            mkbtn(hwnd, B_BACK,   IDC_BTN_BACK,   220, 392, 200, 30);
            break; }
        case SCR_LORE:
            mkbtn(hwnd, B_BACK, IDC_BTN_BACK, 220, 420, 200, 34);
            break;
        case SCR_CONTINUE:
            mkbtn(hwnd, B_CONT, IDC_BTN_CONT, 220, 260, 200, 44);
            mkbtn(hwnd, B_NEW,  IDC_BTN_NEW,  220, 316, 200, 36);
            mkbtn(hwnd, B_BACK, IDC_BTN_BACK, 220, 364, 200, 30);
            break;
        case SCR_WORLD:
            break;
    }
    InvalidateRect(hwnd, NULL, TRUE);
}

/* ----------------------------- Interaction -------------------------------- */
static void EnterWorld(HWND hwnd)
{
    BuildAbilities(); /* class-dependent hotbar */
    g_screen = SCR_WORLD;
    SetTimer(hwnd, 2, 50, NULL);   /* mouse-walk / regen tick */
    LayoutForScreen(hwnd);
    SetFocus(hwnd);
    SaveProfile(); /* real-time: entering the world is persisted instantly */
}

static void TryPickAcorn(HWND hwnd)
{
    int i, best = -1; double bd = 1e9;
    for (i = 0; i < 3; i++) {
        int dx, dy; double d;
        if (g_acorns_arr[i].taken) continue;
        dx = g_px - g_acorns_arr[i].x; dy = g_py - g_acorns_arr[i].y;
        d = sqrt((double)(dx*dx + dy*dy));
        if (d < PICK_R && d < bd) { bd = d; best = i; }
    }
    if (best < 0) return;
    g_acorns_arr[best].taken = 1;
    g_acorns++;
    if (g_questStep == 2 && g_acorns >= 3) g_questStep = 3;
    SaveProfile();               /* real-time autosave on loot */
    InvalidateRect(hwnd, NULL, FALSE);
}

static void TalkCat(HWND hwnd)
{
    if (g_dialogShown) { g_dialogShown = 0; InvalidateRect(hwnd, NULL, FALSE); return; }
    if (g_questStep == 0) {
        wchar_t greet[256];
        swprintf(greet, 256, CAT_GREET, g_nick[0] ? g_nick : L"???");
        ShowDialog(greet, L"");
        g_catTalked = 1;
        g_questStep = 1;
        SaveProfile();
        return;
    }
    if (g_questStep == 1) {
        ShowDialog(CAT_QUEST, L"");
        g_questStep = 2;
        SaveProfile();
        return;
    }
    if (g_questStep == 2) {
        wchar_t b[128];
        swprintf(b, 128, L"\x0416\x0435\x043b\x0443\x0434\x0435\x0439: %d/3. \x041f\x043e\x0434\x043e\x0439\x0434\x0438 \x043a \x0434\x0443\x0431\x0443!", g_acorns);
        ShowDialog(b, L"");
        return;
    }
    if (g_questStep == 3) {
        ShowDialog(CAT_DONE, L"");
        g_questStep = 4;
        SaveProfile();
        return;
    }
    if (g_questStep == 4) {
        /* reward once: +25 XP -> level-up style heal to full */
        g_hpCur = g_hpMax;
        g_questStep = 5;
        ShowDialog(L"\x041c\x0443\x0434\x0440\x0435\x0446 \x043e\x0442 \x041a\x043e\x0442\x0430! \x0416\x0438\x0437\x043d\x044c \x043f\x043e\x043b\x043d\x0430\x044f. \x041d\x043e\x0432\x0430\x044f \x0431\x044b\x043b\x0438\x043d\x0443\x0448\x043a\x0430 \x0441\x043a\x043e\x0440\x043e!", L"");
        SaveProfile();
        InvalidateRect(hwnd, NULL, FALSE);
        return;
    }
    ShowDialog(L"\x041c\x044f\x0443! \x0417\x0430\x0433\x043b\x044f\x043d\x044f\x0439 \x0431\x044b\x043b\x0438\x043d\x0443 \x0437\x0430\x043f\x0438\x0441\x0430\x043d\x0430.", L"");
}

/* Collision test for a single point (shared by keyboard and mouse movement) */
static int BlockedAt(int nx, int ny)
{
    if (nx < 14 || nx > WIN_W - 14) return 1;
    if (ny < 96  || ny > WIN_H - 40) return 1;
    if (abs(nx - OAK_X) < 16 && ny > OAK_Y && ny < OAK_Y + 50) return 1; /* trunk */
    if (nx > 40 && nx < 136 && ny > 120 && ny < 200) return 1;            /* hut1 */
    if (nx > 500 && nx < 600 && ny > 118 && ny < 200) return 1;           /* hut2 */
    if (nx > 150 && nx < 190 && ny > 250 && ny < 276) return 1;           /* well */
    return 0;
}

static void MovePlayer(HWND hwnd, int dx, int dy)
{
    int nx = g_px + dx, ny = g_py + dy;
    if (!BlockedAt(nx, ny)) { g_px = nx; g_py = ny; }
    g_walkDestSet = 0; /* manual keys cancel the mouse walk order */
    /* real-time throttled autosave (every 2s while moving) */
    if (GetTickCount64() - g_lastSave > 2000) SaveProfile();
    InvalidateRect(hwnd, NULL, FALSE);
}

/* Mouse-driven walking: LMB sets destination, hero walks there each tick */
static void WalkToward(HWND hwnd)
{
    double dx, dy, d;
    if (!g_walkDestSet) return;
    dx = g_walkX - g_px; dy = g_walkY - g_py;
    d = sqrt(dx * dx + dy * dy);
    if (d < WALK_SPEED) { g_px = g_walkX; g_py = g_walkY; g_walkDestSet = 0; }
    else {
        int nx = g_px + (int)(dx / d * WALK_SPEED);
        int ny = g_py + (int)(dy / d * WALK_SPEED);
        if (BlockedAt(nx, ny)) { g_walkDestSet = 0; } /* obstacle: stop */
        else { g_px = nx; g_py = ny; }
    }
    if (GetTickCount64() - g_lastSave > 2000) SaveProfile();
    InvalidateRect(hwnd, NULL, FALSE);
}

/* ------------------------------- Abilities -------------------------------- */
static void CastAbility(HWND hwnd, int slot)
{
    ULONGLONG now = GetTickCount64();
    Ability* ab;
    int r, dmg, i;
    if (slot < 0 || slot >= NABILITY || g_selected < 0) return;
    ab = &g_ab[slot];
    if (ab->cd > 1000 && now < ab->cdUntil) return;      /* on cooldown */
    if (g_energyCur < ab->cost) {                        /* not enough energy */
        ShowDialog(L"\x041c\x0430\x043b\x043e \x044d\x043d\x0435\x0440\x0433\x0438\x0438! \x041f\x043e\x0434\x043e\x0436\x0434\x0438 \x043a \x043a\x043e\x0442\x0443 \x2014 \x043e\x043d \x043d\x0430\x043b\x0438\x0442.", L"");
        return;
    }
    g_energyCur -= ab->cost;
    ab->lastCast = now;
    if (ab->cd > 1000) ab->cdUntil = now + ab->cd;

    switch (ab->kind) {
        case AB_HEAL:
            r = ab->power;
            if (g_hpCur < g_hpMax) g_hpCur += r; if (g_hpCur > g_hpMax) g_hpCur = g_hpMax;
            if (g_energyCur < g_energyMax) g_energyCur += 10; if (g_energyCur > g_energyMax) g_energyCur = g_energyMax;
            break;
        case AB_BUFF:
            g_buffUntil = now + 8000; /* +50% damage for 8 s */
            break;
        case AB_PICK:
            for (i = 0; i < 3; i++) {
                int ddx = g_px - g_acorns_arr[i].x, ddy = g_py - g_acorns_arr[i].y;
                if (!g_acorns_arr[i].taken && sqrt((double)(ddx*ddx+ddy*ddy)) < PICK_R + 36) {
                    g_acorns_arr[i].taken = 1; g_acorns++;
                    if (g_questStep == 2 && g_acorns >= 3) g_questStep = 3;
                    break;
                }
            }
            break;
        case AB_DMG: default:
            dmg = ab->power;
            if (now < g_buffUntil) dmg = dmg * 3 / 2;
            r = g_hpCur - dmg; if (r < 0) r = 0; g_hpCur = r;
            break;
    }
    SaveProfile(); /* real-time: ability use is persisted instantly */
    InvalidateRect(hwnd, NULL, FALSE);
}

static void DrawAbilityBar(HDC hdc)
{
    static const wchar_t* AB_KEY[4] = { L"1", L"2", L"3", L"4" };
    ULONGLONG now = GetTickCount64();
    int bx = 250, by = 444, bw = 88, gap = 6, i;
    for (i = 0; i < NABILITY; i++) {
        Ability* ab = &g_ab[i];
        RECT r = { bx + i * (bw + gap), by, bx + i * (bw + gap) + bw, by + 30 };
        ULONGLONG left = 0;
        HBRUSH b;
        int ready = !(ab->cd > 1000 && now < ab->cdUntil) && g_energyCur >= ab->cost;
        b = CreateSolidBrush(ready ? RGB(0x2A,0x30,0x44) : RGB(0x18,0x1A,0x24));
        FillRect(hdc, &r, b); DeleteObject(b);
        DrawFrame(hdc, r, ready ? RGB(0xC8,0x9A,0x3E) : RGB(0x55,0x50,0x44));
        /* cooldown sweep overlay */
        if (ab->cd > 1000 && now < ab->cdUntil) {
            RECT cr = r;
            left = ab->cdUntil - now;
            cr.left = r.left + (LONG)((double)(r.right - r.left) * (1.0 - (double)left / ab->cd));
            b = CreateSolidBrush(RGB(0x10,0x12,0x1A));
            FillRect(hdc, &cr, b); DeleteObject(b);
        }
        TextC(hdc, r.left + 4,  r.top + 2, ab->name,   RGB(0xFF,0xF3,0xC0), g_fSmall, 0);
        TextC(hdc, r.left + 4,  r.top + 16, ab->tag,   ready ? RGB(0x9A,0xAA,0xFF) : RGB(0x77,0x77,0x88), g_fSmall, 0);
        TextC(hdc, r.right - 12, r.top + 2, AB_KEY[i], RGB(0xE8,0xC8,0x5A), g_fSmall, 0);
        if (ab->cd > 1000 && left) {
            wchar_t s[8]; swprintf(s, 8, L"%d", (int)((left + 999) / 1000));
            TextC(hdc, (r.left + r.right)/2, r.top + 8, s, RGB(0xFF,0xFF,0xFF), g_fMed, 1);
        }
    }
}

static void AdvanceTick(HWND hwnd)
{
    int changed = 0;
    ULONGLONG now = GetTickCount64();
    if (g_screen == SCR_WORLD) {
        WalkToward(hwnd);
        /* passive energy regen: +1 every 2 s up to max */
        if (g_energyCur < g_energyMax && now - g_lastRegen >= 2000) {
            g_energyCur++; g_lastRegen = now; changed = 1;
        }
        if (g_buffUntil && now > g_buffUntil) { g_buffUntil = 0; changed = 1; }
        if (g_dialogShown && now > g_dialogUntil) { g_dialogShown = 0; changed = 1; }
        if (changed) InvalidateRect(hwnd, NULL, FALSE);
    }
}

/* ------------------------------ Window proc ------------------------------- */
static LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    static int hasProfile = -1;

    switch (msg) {
        case WM_CREATE: {
            int i;
            HINSTANCE hi = ((LPCREATESTRUCT)lp)->hInstance;
            g_fTitle = CreateFontW(64, 0, 0, 0, FW_BOLD, 0, 0, 0, DEFAULT_CHARSET,
                                  OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, ANTIALIASED_QUALITY, FF_DONTCARE, L"Segoe UI");
            g_fBig   = CreateFontW(28, 0, 0, 0, FW_BOLD, 0, 0, 0, DEFAULT_CHARSET,
                                  OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, ANTIALIASED_QUALITY, FF_DONTCARE, L"Segoe UI");
            g_fMed   = CreateFontW(18, 0, 0, 0, FW_NORMAL, 0, 0, 0, DEFAULT_CHARSET,
                                  OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, ANTIALIASED_QUALITY, FF_DONTCARE, L"Segoe UI");
            g_fSmall = CreateFontW(14, 0, 0, 0, FW_NORMAL, 0, 0, 0, DEFAULT_CHARSET,
                                  OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, ANTIALIASED_QUALITY, FF_DONTCARE, L"Segoe UI");
            for (i = 0; i < 4; i++) { HFONT f = i==0?g_fTitle:i==1?g_fBig:i==2?g_fMed:g_fSmall; (void)f; }
            (void)hi;
            hasProfile = LoadProfile();
            SetTimer(hwnd, 1, 250, NULL); /* dialog auto-hide tick */ SetTimer(hwnd, 2, 50, NULL); /* walk/regen tick (no-op outside world) */
            LayoutForScreen(hwnd);
            return 0;
        }
        case WM_TIMER:
            AdvanceTick(hwnd);
            return 0;
        case WM_CTLCOLORSTATIC:
        case WM_CTLCOLOREDIT:
            SetBkColor((HDC)wp, RGB(0x1A,0x1E,0x2C));
            SetTextColor((HDC)wp, RGB(0xFF,0xFF,0xFF));
            return (LRESULT)GetStockObject(BLACK_BRUSH);
        case WM_DRAWITEM: {
            LPDRAWITEMSTRUCT di = (LPDRAWITEMSTRUCT)lp;
            const wchar_t* txt = NULL;
            COLORREF bg = RGB(0x2A,0x30,0x44), fg = RGB(0xFF,0xFF,0xFF), br = RGB(0xC8,0x9A,0x3E);
            wchar_t buf[64];
            switch (di->CtlID) {
                case IDC_BTN_START: txt = B_START; bg = RGB(0x3A,0x4A,0x8B); break;
                case IDC_BTN_LORE:  txt = B_LORE;  break;
                case IDC_BTN_QUIT:  txt = B_EXIT;  bg = RGB(0x5A,0x2A,0x2A); break;
                case IDC_BTN_BACK:  txt = B_BACK;  break;
                case IDC_BTN_CHOOSE:txt = B_CHOOSE;bg = RGB(0x3A,0x6B,0x3F); break;
                case IDC_BTN_CONT:  txt = B_CONT;  bg = RGB(0x3A,0x6B,0x3F); break;
                case IDC_BTN_NEW:   txt = B_NEW;   break;
                case IDC_CARD_0: case IDC_CARD_1: case IDC_CARD_2: {
                    int idx = di->CtlID - IDC_CARD_0;
                    RECT r = di->rcItem;
                    HBRUSH b = CreateSolidBrush(di->itemState & ODS_SELECTED ? RGB(0x2A,0x34,0x50) : RGB(0x1A,0x1E,0x2C));
                    FillRect(di->hDC, &r, b); DeleteObject(b);
                    if (g_selected == idx) {
                        HPEN p = CreatePen(PS_SOLID, 3, RGB(0xFF,0xE9,0x7A));
                        HPEN o = (HPEN)SelectObject(di->hDC, p);
                        SelectObject(di->hDC, GetStockObject(NULL_BRUSH));
                        Rectangle(di->hDC, r.left, r.top, r.right, r.bottom);
                        SelectObject(di->hDC, o); DeleteObject(p);
                    }
                    return TRUE; }
                default: {
                    if (GetDlgItemTextW(hwnd, (int)di->CtlID, buf, 64)) txt = buf; else txt = L"";
                }
            }
            {
                RECT r = di->rcItem;
                HBRUSH b = CreateSolidBrush(bg);
                FillRect(di->hDC, &r, b); DeleteObject(b);
                DrawFrameAt(di->hDC, r, br);
                SetBkMode(di->hDC, TRANSPARENT);
                SetTextColor(di->hDC, fg);
                SelectObject(di->hDC, g_fMed);
                DrawTextW(di->hDC, txt, -1, &r, DT_CENTER | DT_VCENTER | DT_SINGLELINE);
            }
            return TRUE;
        }
        case WM_PAINT:
            OnPaint(hwnd);
            return 0;
        case WM_KEYDOWN:
            if (g_screen != SCR_WORLD) return 0;
            switch (wp) {
                case '1': CastAbility(hwnd, 0); break;
                case '2': CastAbility(hwnd, 1); break;
                case '3': CastAbility(hwnd, 2); break;
                case '4': CastAbility(hwnd, 3); break;
                case VK_LEFT:  case 'A': MovePlayer(hwnd, -8, 0); break;
                case VK_RIGHT: case 'D': MovePlayer(hwnd,  8, 0); break;
                case VK_UP:    case 'W': MovePlayer(hwnd, 0, -8); break;
                case VK_DOWN:  case 'S': MovePlayer(hwnd, 0,  8); break;
                case 'E': {
                    int dx = g_px - CAT_X, dy = g_py - CAT_Y;
                    if (sqrt((double)(dx*dx+dy*dy)) < TALK_R) TalkCat(hwnd);
                    else TryPickAcorn(hwnd);
                    break; }
                case VK_ESCAPE:
                    KillTimer(hwnd, 2);
                    g_walkDestSet = 0;
                    g_screen = SCR_CONTINUE; /* back to menu keeps profile */
                    LayoutForScreen(hwnd);
                    break;
            }
            return 0;
        case WM_LBUTTONDOWN:
            if (g_screen == SCR_WORLD) {
                if (g_dialogShown) { g_dialogShown = 0; InvalidateRect(hwnd, NULL, FALSE); }
                else {
                    /* mouse-to-walk: hero walks to the clicked point */
                    int mx = GET_X_LPARAM(lp), my = GET_Y_LPARAM(lp);
                    if (mx >= 14 && mx <= WIN_W - 14 && my >= 96 && my <= WIN_H - 40 &&
                        !BlockedAt(mx, my)) {
                        g_walkX = mx; g_walkY = my; g_walkDestSet = 1;
                        InvalidateRect(hwnd, NULL, FALSE);
                    }
                }
            }
            return 0;
        case WM_COMMAND:
            switch (LOWORD(wp)) {
                case IDC_BTN_START:
                    if (hasProfile == 1) { g_screen = SCR_CONTINUE; }
                    else                 { g_screen = SCR_SELECT; }
                    LayoutForScreen(hwnd);
                    break;
                case IDC_BTN_LORE:
                    g_screen = SCR_LORE; LayoutForScreen(hwnd); break;
                case IDC_BTN_QUIT:
                    DestroyWindow(hwnd); break;
                case IDC_BTN_BACK:
                    g_screen = (hasProfile == 1) ? SCR_CONTINUE : SCR_LAUNCH;
                    LayoutForScreen(hwnd);
                    break;
                case IDC_CARD_0: case IDC_CARD_1: case IDC_CARD_2: {
                    int idx = LOWORD(wp) - IDC_CARD_0;
                    g_selected = idx;
                    g_hpMax = g_class[idx].hp; g_hpCur = g_class[idx].hp;
                    g_energyMax = g_class[idx].energy; g_energyCur = g_class[idx].energy;
                    BuildAbilities(); /* hotbar preview follows the class */
                    LayoutForScreen(hwnd); /* repaint selection */
                    break; }
                case IDC_BTN_CHOOSE: {
                    wchar_t nick[64];
                    if (g_selected < 0) { MessageBoxW(hwnd, B_NEED, APP_TITLE, MB_OK | MB_ICONWARNING); break; }
                    GetWindowTextW(g_editNick, nick, 63);
                    if (!nick[0]) { MessageBoxW(hwnd, H_WARN, APP_TITLE, MB_OK | MB_ICONWARNING); break; }
                    lstrcpynW(g_nick, nick, 64);
                    g_questStep = 0; g_acorns = 0; g_catTalked = 0;
                    g_px = 320; g_py = 380;
                    memset(g_acorns_arr, 0, sizeof(g_acorns_arr));
                    hasProfile = 1;
                    SaveProfile(); /* real-time: character creation persists now */
                    EnterWorld(hwnd);
                    break; }
                case IDC_BTN_CONT:
                    EnterWorld(hwnd);
                    break;
                case IDC_BTN_NEW:
                    hasProfile = 0;
                    g_selected = -1; g_nick[0] = 0;
                    g_screen = SCR_SELECT;
                    LayoutForScreen(hwnd);
                    break;
            }
            return 0;
        case WM_CLOSE:
            SaveProfile(); /* persist on exit */
            DestroyWindow(hwnd);
            return 0;
        case WM_DESTROY:
            KillTimer(hwnd, 1);
            PostQuitMessage(0);
            return 0;
    }
    return DefWindowProcW(hwnd, msg, wp, lp);
}

/* helper: frame at rect with color (DrawFrame expects RECT value) */
static void DrawFrameAt(HDC hdc, RECT r, COLORREF c)
{
    HPEN pen = CreatePen(PS_SOLID, 2, c);
    HPEN old = (HPEN)SelectObject(hdc, pen);
    SelectObject(hdc, GetStockObject(NULL_BRUSH));
    Rectangle(hdc, r.left, r.top, r.right, r.bottom);
    SelectObject(hdc, old);
    DeleteObject(pen);
}

int WINAPI WinMain(HINSTANCE hi, HINSTANCE ph, LPSTR cl, int cs)
{
    WNDCLASSW wc = {0};
    HWND hwnd;
    MSG m;
    RECT rc = {0, 0, WIN_W, WIN_H};
    DWORD style = WS_OVERLAPPEDWINDOW & ~(WS_THICKFRAME | WS_MAXIMIZEBOX);
    int sw = GetSystemMetrics(SM_CXSCREEN), sh = GetSystemMetrics(SM_CYSCREEN);
    int x, y;

    AdjustWindowRect(&rc, style, FALSE);
    x = (sw - (rc.right - rc.left)) / 2;
    y = (sh - (rc.bottom - rc.top)) / 2;

    wc.lpfnWndProc = WndProc;
    wc.hInstance = hi;
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    wc.hbrBackground = (HBRUSH)GetStockObject(BLACK_BRUSH);
    wc.lpszClassName = L"YavProtoWnd";
    RegisterClassW(&wc);

    hwnd = CreateWindowExW(0, wc.lpszClassName, APP_TITLE, style,
                           x, y, rc.right - rc.left, rc.bottom - rc.top,
                           NULL, NULL, hi, NULL);
    ShowWindow(hwnd, SW_SHOW);
    UpdateWindow(hwnd);

    while (GetMessageW(&m, NULL, 0, 0)) {
        TranslateMessage(&m);
        DispatchMessageW(&m);
    }
    (void)ph; (void)cl; (void)cs;
    return (int)m.wParam;
}
